import {writeFileSync,existsSync,readFileSync} from 'node:fs';
import {defaultCase,newRegion} from '../src/domain/model.ts';
import {solveDetailed} from '../src/analysis/solid/extendedField.ts';
import {localStressAt} from '../src/analysis/solid/field.ts';
import {poleMesh,RESOLUTIONS} from '../src/analysis/solid/mesh.ts';
import {curveMesh,curvedEndLoads,solveCurved} from '../src/analysis/solid/curved.ts';
import {extendMesh} from '../src/analysis/solid/extendMesh.ts';
import {orthotropicD} from '../src/analysis/solid/kernel.ts';
import {prepareRecovery} from '../src/analysis/solid/curvedRecovery.ts';
const file='verification/results/p09-studies.json',report=process.argv.includes('--resume')&&existsSync(file)?JSON.parse(readFileSync(file,'utf8')):{mesh:[],boundary:[],notes:'Predeclared gates: energy 2%, nonsingular probe stress 5%; no ultimate capacity/physical validation.'},save=()=>writeFileSync(file,JSON.stringify(report,null,2));
const p=defaultCase();p.soil='Fixed';p.diameters={butt:.3,ground:.3,tip:.3};const knot=newRegion(p,'knot'),graded=newRegion(p),drill=newRegion(p,'drilling');graded.zMin=1;graded.zMax=2;graded.shape.centreX=graded.shape.centreY=0;graded.decay={pattern:'heart',progression:'source',sourceZ:1.5,exponent:2,shellDepth:.03};drill.zMin=1.5-drill.drilling.diameter/2;drill.zMax=1.5+drill.drilling.diameter/2;
for(const kind of ['knot','graded','drilling'])for(const level of ['coarse','medium','fine']){if(report.mesh.some(r=>r.kind===kind&&r.level===level))continue;p.regions=[kind==='knot'?knot:kind==='graded'?graded:drill];const probes=kind==='drilling'?[[.08,-.06,1.52],[.07,-.055,1.50],[.03,-.04,1.50]]:kind==='knot'?[[.1,0,1],[-.1,0,1],[.06,.04,1]]:[[.10,0,1.5],[.04,0,1.5],[-.1,0,1.5]];try{const f=solveDetailed(p,level);report.mesh.push({kind,level,nodes:f.nodes,elements:f.elements,energy:f.energy,residual:f.residual,ms:f.elapsedMs,probes,MPa:probes.map(q=>{const v=localStressAt(f,...q);return v===null?null:v/1e6;})});}catch(error){report.mesh.push({kind,level,error:error.message});}console.log(report.mesh.at(-1));save();}
const r=newRegion(p,'void');r.zMin=1.6;r.zMax=2.2;r.shape={type:'ellipse',centreX:.02,centreY:0,radiusX:.06,radiusY:.07,angle:0,profile:'rounded'};p.regions=[r];const original=curveMesh(poleMesh(p,{...RESOLUTIONS.coarse,marginDiameters:1,capRadial:2}),p,true),D=orthotropicD(p.material.E),probes=[[.115,0,1.9],[.04,0,1.58],[.04,0,2.22],[-.115,0,1.9],[.09,0,1.75]];
for(const extension of [0,.3,.6]){if(report.boundary.some(r=>r.extension===extension))continue;try{const m=extendMesh(original,p,extension),end=curvedEndLoads(m,[1000,0,0],[1000*(p.length-p.embedment-m.zMax),0]),fixed=new Map(m.bottom.flatMap(n=>[0,1,2].map(k=>[n*3+k,0]))),s=solveCurved(m,D,end.loads,fixed),rec=prepareRecovery(m,s.displacements,D),f={...rec,elements:m.tets.length,zMin:m.zMin,zMax:m.zMax},preserved=original.points.every(a=>m.points.some(b=>a.every((v,k)=>Math.abs(v-b[k])<1e-12)));report.boundary.push({extension,nodes:m.points.length,elements:m.tets.length,originalGeometryPreserved:preserved,residual:s.relativeResidual,probes,MPa:probes.map(q=>{const v=localStressAt(f,...q);return v===null?null:v/1e6;}),ms:s.elapsedMs});}catch(error){report.boundary.push({extension,error:error.message});}console.log(report.boundary.at(-1));save();}
report.assessments={};for(const kind of ['knot','graded','drilling']){const rows=report.mesh.filter(r=>r.kind===kind),a=rows[1],b=rows[2];report.assessments[kind]=a?.energy&&b?.energy?{energyChange:Math.abs(b.energy/a.energy-1),probeChanges:b.MPa.map((v,i)=>v===null||a.MPa[i]===null?null:Math.abs(v/a.MPa[i]-1)),qualified:false}:{qualified:false};}const a=report.boundary[1],b=report.boundary[2];if(a?.MPa&&b?.MPa)report.assessments.cavityBoundary={changes:b.MPa.map((v,i)=>v===null||a.MPa[i]===null?null:Math.abs(v/a.MPa[i]-1)),qualified:false};save();

for(const kind of ['knot','graded','drilling']){const a=report.assessments[kind];a.meshGatePassed=a.energyChange<.02&&a.probeChanges.every(v=>v!==null&&v<.05);}
report.assessments.cavityBoundary.fixedMeshBoundaryGatePassed=report.boundary.every(r=>r.originalGeometryPreserved)&&report.assessments.cavityBoundary.changes.every(v=>v!==null&&v<.05);save();
