import {writeFileSync} from 'node:fs';
import {defaultCase,newRegion,validateCase,conditionAt} from '../src/domain/model.ts';
import {normaliseSketch,insidePolygon,simplePolygon} from '../src/domain/sketch.ts';
import {sectionProperties,solvePole,beamKinematicsAt,scaleUnitResult} from '../src/analysis/beam.ts';
import {prepareHeightProfile,profileFromBasis} from '../src/analysis/heightProfile.ts';
import {orthotropicD} from '../src/analysis/solid/kernel.ts';
import {rotateTimber,materialAt} from '../src/analysis/solid/material.ts';
import {curvedElement,mappedPoint,volumeRule} from '../src/analysis/solid/curved.ts';
import {volumeMesh} from '../src/analysis/solid/volumeMesh.ts';
import {drillMesh} from '../src/analysis/solid/drillMesh.ts';
import {solveDetailed} from '../src/analysis/solid/extendedField.ts';
import {localStressAt} from '../src/analysis/solid/field.ts';
const checks=[],check=(name,pass,data)=>{checks.push({name,pass,data});if(!pass)throw Error(name+': '+JSON.stringify(data));},close=(name,v,target,tol)=>check(name,Math.abs(v-target)<=tol,{v,target,tol});
const p=defaultCase();p.soil='Fixed';p.diameters={butt:.3,ground:.3,tip:.3};
const outline=[[-.06,-.04],[.06,-.04],[.06,.04],[-.06,.04]],shape=normaliseSketch(outline),r={...newRegion(p,'void'),shape,zMin:1,zMax:2};p.regions=[r];
check('Synthetic sketch accepted',!validateCase(p).length);check('Self intersection rejected',!simplePolygon([[0,0],[1,1],[1,0],[0,1]]));check('Concave notch stays sound',!insidePolygon([[0,0],[1,0],[1,1],[.5,.4],[0,1]],.5,.8));check('Sketch centre is void',conditionAt(p,0,0,1.5).voided);check('Outside sketch is timber',!conditionAt(p,.09,0,1.5).voided);
const section=sectionProperties(p,1.5,180,512);close('Sketch removed area against rectangle',Math.PI*.15**2*(1-section.remaining),.12*.08,1e-4);const translated=structuredClone(p);translated.regions[0].shape.centreX=.04;check('Dragging changes geometry',conditionAt(translated,.09,0,1.5).voided&&!conditionAt(translated,-.05,0,1.5).voided);check('Sketch round trip',!validateCase(JSON.parse(JSON.stringify(p))).length);
const D=orthotropicD(8e9),identity=rotateTimber(D,[0,0,1]),transverse=rotateTimber(D,[1,0,0]);close('Fibre identity preserves stiffness',Math.max(...D.flatMap((row,i)=>row.map((v,j)=>Math.abs(v-identity[i][j])))),0,2e-6);close('90 degree fibre swaps axial stiffness',transverse[0][0],D[2][2],1e-5);
const a=.73,n=[Math.sin(a),0,Math.cos(a)],rot=rotateTimber(D,n);close('Rotated constitutive reciprocity',Math.max(...rot.flatMap((row,i)=>row.map((v,j)=>Math.abs(v-rot[j][i])))),0,1e-5);
// Independent strain transformation, rather than reproducing the tensor formula.
const e=[[.001,.0002,-.0003],[.0002,-.0004,.0001],[-.0003,.0001,.002]],Q=[[Math.cos(a),0,Math.sin(a)],[0,1,0],[-Math.sin(a),0,Math.cos(a)]],local=Q.map((_,i)=>Q.map((_,j)=>e.reduce((sum,row,k)=>sum+row.reduce((v,x,l)=>v+Q[k][i]*x*Q[l][j],0),0))),voigt=t=>[t[0][0],t[1][1],t[2][2],2*t[0][1],2*t[1][2],2*t[0][2]],energy=(v,C)=>v.reduce((s,x,i)=>s+x*C[i].reduce((v,d,j)=>v+d*voigt(e)[j],0),0),ev=voigt(local),reference=ev.reduce((s,x,i)=>s+x*D[i].reduce((v,d,j)=>v+d*ev[j],0),0);close('Rotation agrees with independent strain energy',energy(voigt(e),rot)/reference,1,1e-12);
p.regions=[];const basis=prepareHeightProfile(p),profile=profileFromBasis(basis,90,1),ground=profile.find(r=>Math.abs(r.z)<1e-6),expected=p.material.compression*Math.PI*.15**3/4/(1000*(p.length-p.embedment));close('Height chart uniform circular cantilever limit',ground.capacityApplied,expected,.01*expected);close('Any-direction envelope on round sound pole',ground.usageWorst,ground.usageApplied,.002);close('Chart linear load scaling',profileFromBasis(basis,90,3).find(r=>Math.abs(r.z)<1e-6).usageApplied,ground.usageApplied*3,1e-12);check('Zero load keeps capacity',profileFromBasis(basis,90,0).find(r=>Math.abs(r.z)<1e-6).capacityApplied>0);check('Zero load has zero usage',profileFromBasis(basis,90,0).every(r=>r.usageWorst===0));
const knot=newRegion(p,'knot');p.regions=[knot];check('Knot creates normal-shear coupling',Math.abs(materialAt(p,knot.shape.centreX,0,1)[2][5])>1e5);const decay=newRegion(p);decay.zMin=1;decay.zMax=2;decay.shape.centreX=decay.shape.centreY=0;decay.decay={pattern:'heart',progression:'source',sourceZ:1.5,exponent:2,shellDepth:.03};p.regions=[decay];check('Graded material varies axially from the source section',materialAt(p,0,0,1.5)[2][2]<materialAt(p,0,0,1.75)[2][2]);
const soundResult=solvePole({...p,regions:[]}),z=.87,L=p.length-p.embedment,EI=p.material.E*Math.PI*.15**4/4,kin=beamKinematicsAt(soundResult,z);close('Exact displacement transfer agrees with cantilever',kin.ux,1000*z*z*(3*L-z)/(6*EI),1e-9);close('Exact rotation transfer agrees with cantilever',kin.rx,1000*z*(2*L-z)/(2*EI),1e-9);close('Exact curvature transfer agrees with cantilever',kin.kx,1000*(L-z)/EI,1e-9);close('Unit scaling preserves exact rotation',beamKinematicsAt(scaleUnitResult(soundResult,3),z).rx,kin.rx*3,1e-12);
const mesh=volumeMesh(p),ns=mesh.tets[0],pts=ns.map(i=>mesh.points[i]),K=curvedElement(pts,D).K,energyK=(K,u)=>u.reduce((s,x,i)=>s+x*u.reduce((v,y,j)=>v+K[i*30+j]*y,0)/2,0),u=pts.flatMap(([x,y,z])=>[.001*x,.002*y,.003*z]);check('Quadratic material stiffness is symmetric',Math.max(...K.map((v,i)=>Math.abs(v-K[(i%30)*30+Math.floor(i/30)])))<1e-5);check('Affine displacement has positive energy',energyK(K,u)>0);
const centre=mappedPoint(pts,[.25,.25,.25,.25]).x,gradedK=curvedElement(pts,x=>D.map(row=>row.map(v=>v*(1+x[0]*.8)))).K;close('Quadrature graded elasticity agrees with affine volume integral',energyK(gradedK,u)/energyK(K,u),1+centre[0]*.8,1e-11);
const drill=newRegion(p,'drilling');drill.zMin=1.5-drill.drilling.diameter/2;drill.zMax=1.5+drill.drilling.diameter/2;p.regions=[drill];const dm=drillMesh(p);check('Blind drill has free bore and constrained remote cuts',dm.artificial.length>0&&dm.artificial.length<dm.mesh.points.length);check('Bore removes material without zero-stiffness elements',dm.mesh.factors.every(f=>f===1));
for(const kind of ['knot','graded','drilling']){p.regions=[kind==='knot'?knot:kind==='graded'?decay:drill];const f=solveDetailed(p,'coarse');check(kind+' solid converges',f.residual<2e-9,{nodes:f.nodes,elements:f.elements,ms:f.elapsedMs,energy:f.energy,residual:f.residual});check(kind+' external force and moment balance',f.diagnostics.forceBalanceN<.001&&f.diagnostics.momentBalanceNm<.001,f.diagnostics);check(kind+' strain energy equals boundary/load work',f.diagnostics.relativeWorkError<1e-7,f.diagnostics);const q=kind==='drilling'?[.08,-.06,1.52]:[.10,0,kind==='knot'?1:1.5],v=localStressAt(f,...q);check(kind+' has recovered solved stress',v!==null&&Number.isFinite(v),{point:q,MPa:v===null?null:v/1e6});if(kind==='drilling')check('No recovered material inside bore',localStressAt(f,.1,-.1,1.5)===null);writeFileSync('verification/results/p09.json',JSON.stringify({scope:'Numerical verification; local peak/boundary and physical qualification remain separate',checks},null,2));}
console.log(checks.length+' P09 checks passed');
