import {filmCase,filmSectionHeight} from '../src/lessons/filmCases.ts';
import {writeFileSync,readFileSync} from 'node:fs';
import {defaultCase,newRegion,validateCase} from '../src/domain/model.ts';
import {SPECIES,referenceMaterial,materialErrors,bendingResistance} from '../src/domain/species.ts';
import {solvePole,stationAt,utilisationAt} from '../src/analysis/beam.ts';
import {prepareHeightProfile,profileFromBasis} from '../src/analysis/heightProfile.ts';
import {placeholderAssessment} from '../src/inspection/placeholder.ts';
import {assessSolid} from '../src/analysis/solid/assessment.ts';
import {filmLabelPose} from '../src/lessons/filmLabels.ts';
const checks=[];function check(name,pass,data){checks.push({name,pass,data});if(!pass)throw Error(name);}
const p=defaultCase();p.soil='Fixed';p.loadKN=1;p.diameters={butt:.3,ground:.3,tip:.3};
check('Legacy P18 cases preserve their teaching material',validateCase(p).length===0&&p.material.tension===35e6&&p.material.compression===25e6);
for(const s of SPECIES){const m=referenceMaterial(s);check(s.name+': explicit reference or no invented properties',m?materialErrors(s.id,m).length===0:!s.reference);}
const species=SPECIES.find(s=>s.id==='southern-pine'),m=referenceMaterial(species);const ref={...p,species:species.id,material:m};
const result=solvePole(ref),expected=55.2e6*Math.PI*.3**3/32/(p.length-p.embedment)/1000;
check('ANSI bending reference reproduces cantilever Fb Z / H',Math.abs(result.timberLimitKN/expected-1)<.004,{actual:result.timberLimitKN,expected});
check('Bending reference does not invent direct fibre strengths',m.tension===undefined&&m.compression===undefined);
check('Doubling Fb doubles bending capacity without changing movement',Math.abs(solvePole({...ref,material:{basis:'user-bending',E:m.E,bending:m.bending*2,source:'Numerical test'}}).timberLimitKN/result.timberLimitKN-2)<1e-5);
const stiff=solvePole({...ref,material:{basis:'user-bending',E:m.E*2,bending:m.bending,source:'Numerical test'}});
check('Stiffness changes deflection, not sound fixed-cantilever capacity',Math.abs(stiff.tipMovement/result.tipMovement-.5)<1e-5&&Math.abs(stiff.timberLimitKN/result.timberLimitKN-1)<1e-5);
const df=SPECIES.find(s=>s.id==='douglas-fir-coastal');check('Through-bored Douglas fir uses published 5 percent reduction',referenceMaterial(df,true).bending===52.44e6);
check('Edited published data cannot retain a published-reference label',materialErrors(species.id,{...m,bending:80e6}).length>0);
check('Unknown species and incomplete custom properties are rejected',materialErrors('made-up',m).length>0&&materialErrors('spotted-gum',{basis:'user-bending',E:0,bending:30e6,source:''}).length>0);
check('Australian species accept explicitly supplied data',validateCase({...p,species:'spotted-gum',material:{basis:'user-bending',E:16e9,bending:60e6,source:'Verification example, not an assigned grade'}}).length===0);
const r=newRegion(ref,'void');r.zMin=0;r.zMax=2;r.shape={type:'ellipse',centreX:.045,centreY:0,radiusX:.08,radiusY:.07,angle:0,profile:'constant'};const damaged={...ref,regions:[r]},d=solvePole(damaged);
check('Eccentric cavity reduces sourced-reference capacity',d.timberLimitKN<result.timberLimitKN,{sound:result.timberLimitKN,damaged:d.timberLimitKN});
check('Stress sign still selects the appropriate defect factor',bendingResistance(m,1,{tension:.2,compression:.6})===m.bending*.2&&bendingResistance(m,-1,{tension:.2,compression:.6})===m.bending*.6);
const rows=profileFromBasis(prepareHeightProfile(damaged),damaged.bearing,damaged.loadKN,false),gl=rows.find(r=>r.z===0),st=stationAt(d,0);
check('Section utilisation and height chart share new strength basis',Math.abs(gl.usageApplied-st.usage)<1e-6&&Number.isFinite(utilisationAt(damaged,st,-.15,0)));
check('Inspection MPa conversion uses selected bending reference',placeholderAssessment(ref,1).soundReferenceMPa===55.2);
const solid=assessSolid(ref,{curved:null});check('Pole Fb cannot qualify local direct-stress capacity',solid.governing===null&&solid.unassessed.includes('Direct fibre tension/compression strengths'));
const label={side:'left',start:1.2,end:5.4,y:180};const frames=Array.from({length:301},(_,i)=>filmLabelPose(label,i/20,15));
check('Label screen side and location do not follow projected pole x',frames.every(f=>f.x===32&&f.y===180&&f.side==='left'));
check('Labels disappear after a short window',frames.filter((f,i)=>i/20<1.2||i/20>=5.4).every(f=>f.alpha===0));
check('Label fade is continuous and bounded',frames.every(f=>f.alpha>=0&&f.alpha<=1)&&frames.slice(1).every((f,i)=>Math.abs(f.alpha-frames[i].alpha)<=.200001));
const shot=filmCase(4,3),shotResult=solvePole(shot);check('Walkthrough critical section displays the actual solved critical height',filmSectionHeight(4,3,shotResult.timberZ)===shotResult.timberZ&&shotResult.timberZ!==1.7);
const films=JSON.parse(readFileSync('public/videos/manifest.json','utf8'));
check('Fifth walkthrough has six narrated and captioned chapters',films.length===7&&films[4].chapters.length===6&&films[4].chapters.every(ch=>ch.audio&&ch.cues.length&&ch.labels.every(l=>l.end-l.start>=3)));
writeFileSync('verification/results/p19.json',JSON.stringify({scope:'Material provenance, bending criterion, legacy compatibility and film label timing; not physical validation',checks},null,2));console.log(`${checks.length} P19 checks passed.`);
