import assert from 'node:assert/strict';
import {BUILD_VERSION} from '../src/domain/build.ts';
import fs from 'node:fs';
import path from 'node:path';
import {conditionAt,defaultCase,diameterAt,newRegion,normaliseCase,safeAssetFilePart,validateCase,drillingBounds} from '../src/domain/model.ts';
import {solvePole,sectionProperties} from '../src/analysis/beam.ts';
import {COUNTRIES,applyEmbedmentHeuristic,matchPoleClass} from '../src/domain/countries.ts';
import {displayForce,forceFromDisplay,displayPoleLength,poleLengthFromDisplay,displaySmallLength,smallLengthFromDisplay,displayStress,unitLabels,formatFeetInches,formatPoleLength} from '../src/domain/units.ts';
import {resolveBreakState} from '../src/domain/break.ts';
import {drillingScenePlacement} from '../src/scene/drillingGeometry.ts';
import {prepareHeightProfile,profileFromBasis} from '../src/analysis/heightProfile.ts';

const root=path.resolve(import.meta.dirname,'..'),checks=[];
function check(id,name,fn){try{fn();checks.push({id,name,pass:true});}catch(error){checks.push({id,name,pass:false,error:error instanceof Error?error.message:String(error)});}}
const near=(actual,expected,tolerance=1e-9)=>assert.ok(Math.abs(actual-expected)<=tolerance,`${actual} != ${expected}`);

check('FR-001','asset ID storage, validation and safe export name',()=>{const p=defaultCase();p.assetId='Pole / 42: North';assert.equal(validateCase(p).length,0);assert.equal(safeAssetFilePart(p.assetId),'Pole-42-North');p.assetId='x'.repeat(256);assert.ok(validateCase(p).some(x=>x.includes('Asset ID')));});
check('FR-002','reference calculator units round-trip through SI',()=>{near(poleLengthFromDisplay(displayPoleLength(10.5,'imperial'),'imperial'),10.5);near(smallLengthFromDisplay(displaySmallLength(.305,'imperial'),'imperial'),.305);near(forceFromDisplay(displayForce(8,'imperial'),'imperial'),8);near(displayForce(8,'imperial'),1798.47155096768,1e-8);near(displayStress(27.5,'imperial'),3.988537788,1e-6);assert.deepEqual([unitLabels.imperial.force,unitLabels.imperial.stress],['lbf','kpsi']);});
check('FR-002','country changes select regional defaults while explicit unit controls remain available',()=>{const app=fs.readFileSync(path.join(root,'src/ui/App.tsx'),'utf8'),fn=app.slice(app.indexOf('function setGlobalCountry'),app.indexOf('function applyPoleClass'));assert.match(fn,/unitSystem: code === "US" \? "imperial" : "metric"/);assert.ok(app.includes('onClick={() => setGlobalUnits(u)}'));});
check('FR-003','country defaults and embedment heuristics',()=>{near(applyEmbedmentHeuristic(12,'NZ'),2);near(applyEmbedmentHeuristic(12,'US'),1.8096);assert.equal(COUNTRIES.US.defaultUnits,'imperial');});
check('FR-004','supplied Goldpine and ANSI pole class tables',()=>{const nz=COUNTRIES.NZ.poleClasses.find(x=>x.id==='nz-goldpine-12m-12kn');assert.ok(nz);near(nz.groundDiameterM,.345);near(nz.tipDiameterM,.265);const us=COUNTRIES.US.poleClasses.find(x=>x.id==='us-ansi-1-40ft');assert.ok(us);near(us.tipDiameterM,27*.0254/Math.PI);assert.match(us.source,/powline\.com\/files\/pls_pole\/ansi\/ansi_O5-1\.html/);assert.match(us.source,/as-is.*verify/i);assert.equal(matchPoleClass('NZ','radiata-pine',12,.35)?.id,nz.id);});
check('FR-005','Pole Insights names current user-facing surfaces',()=>{assert.match(fs.readFileSync(path.join(root,'index.html'),'utf8'),/<title>Pole Insights · InnerView Insights<\/title>/);assert.match(fs.readFileSync(path.join(root,'src/ui/App.tsx'),'utf8'),/P28 · P26 base/);});
check('FR-006','load application height changes structural response',()=>{const high=defaultCase(),low=structuredClone(high);high.loadHeight=high.length-high.embedment;low.loadHeight=3;const a=solvePole(high,20),b=solvePole(low,20);assert.ok(b.tipMovement<a.tipMovement);assert.ok(b.limitKN>a.limitKN);});
check('FR-006','decimal load offsets remain attached to the rounded beam mesh',()=>{const p=defaultCase();p.length=15.12;p.embedment=3.13;p.diameters={butt:.5379437076506063,ground:.48701412586119974,tip:.3246760839074665};p.loadKN=10.31;p.bearing=47;p.loadHeight=11.689999999999998;const result=solvePole(p);assert.ok(result.tipMovement>0,'applied load produces movement');assert.ok(result.stations.some(s=>Math.max(Math.abs(s.stressMin),Math.abs(s.stressMax))>0),'applied load produces stress');assert.ok(Number.isFinite(result.limitKN)&&result.limitKN>0,'capacity is finite and positive');});
check('FR-006','load control is presented as an offset from the pole tip',()=>{const app=fs.readFileSync(path.join(root,'src/ui/App.tsx'),'utf8');assert.match(app,/label="Load application offset"/);assert.match(app,/h-loadApplicationHeight\(p\)/);assert.match(app,/loadHeight: h-poleLengthFromDisplay/);});
check('FR-006','load-point slider lock defaults on and relocks after adjustment',()=>{const app=fs.readFileSync(path.join(root,'src/ui/App.tsx'),'utf8');assert.match(app,/\[loadPointLocked, setLoadPointLocked\] = useState\(true\)/);assert.match(app,/Lock load point slider/);assert.match(app,/\{!loadPointLocked && \(/);assert.match(app,/setLoadPointLocked\(true\)/);});
check('FR-007','Legacy Detect preference remains importable; system preference filters related UI',()=>{const p=normaliseCase({...defaultCase(),showDetect:false}),app=fs.readFileSync(path.join(root,'src/ui/App.tsx'),'utf8'),videos=fs.readFileSync(path.join(root,'src/lessons/VideoLibrary.tsx'),'utf8');assert.equal(p.showDetect,false);assert.equal(normaliseCase({...defaultCase(),showDetect:undefined}).showDetect,true);assert.match(app,/showDetect=\{preferences\.detect\}/);assert.match(videos,/showDetect \? films : films\.filter/);});
check('FR-008','isolated Cloudflare staging command exists',()=>{const pkg=JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8'));assert.match(pkg.scripts['deploy:staging'],/pole-insights-staging/);assert.doesNotMatch(pkg.scripts['deploy:staging'],/production/i);});
check('FR-009','below-ground inspection range is represented and valid',()=>{const p=defaultCase(),detect=fs.readFileSync(path.join(root,'src/ui/DetectSection.tsx'),'utf8'),app=fs.readFileSync(path.join(root,'src/ui/App.tsx'),'utf8');assert.ok(-p.embedment<0);assert.equal(validateCase(p).length,0);assert.match(detect,/-pole\.embedment/);assert.doesNotMatch(app,/view === "Test" \? 0 : -cases\[k\]\.embedment/);assert.match(app,/clamp\(\s*z,\s*-cases\[k\]\.embedment/);});
check('FR-010','chipping removes tapered exterior material and validates facets',()=>{const p=defaultCase(),chip=newRegion(p,'chipping'),sound={...p,regions:[]},R=diameterAt(p,chip.zMin)/2;p.regions=[chip];assert.equal(conditionAt(p,0,0,chip.zMin).voided,false,'pole centre remains timber');assert.equal(conditionAt(p,0,R-.005,chip.zMin).voided,true,'outside face is chipped at the bottom');assert.equal(conditionAt(p,0,R-chip.chipping.depth-.005,chip.zMin).voided,false,'timber inside the chipped depth remains');assert.ok(sectionProperties(p,chip.zMin).area<sectionProperties(sound,chip.zMin).area);assert.ok(Math.abs(sectionProperties(p,chip.zMax).area-sectionProperties(sound,chip.zMax).area)<1e-8,'top feathers into the original circumference');chip.chipping.facets=5;assert.ok(validateCase(p).some(x=>x.includes('Chipping')));chip.chipping.facets=8;assert.equal(validateCase(p).length,0);});
check('FR-011','angled drilling runs down and inward from the outside entry',()=>{const p=defaultCase(),drill=newRegion(p,'drilling');drill.drilling.inclination=45;drill.drilling.entryHeight=.8;Object.assign(drill,drillingBounds(drill.drilling));p.regions=[drill];assert.ok(drill.zMin<.8&&drill.zMax>.79);assert.ok(sectionProperties(p,.75).area<sectionProperties({...p,regions:[]},.75).area);const placement=drillingScenePlacement(drill.drilling.bearing,drill.drilling.inclination,diameterAt(p,.8)/2,drill.drilling.depth),inside=placement.entry.map((v,i)=>v+placement.inward[i]*drill.drilling.depth);assert.ok(inside[1]<placement.entry[1],'inner end is below the outside entry');assert.ok(Math.hypot(inside[0],inside[2])<Math.hypot(placement.entry[0],placement.entry[2]),'inner end is closer to the pole centre');assert.equal(validateCase(p).length,0);});
check('FR-012','break display is opt-in and annotates the intact loaded pole',()=>{const p=defaultCase(),result=solvePole(p,20),scene=fs.readFileSync(path.join(root,'src/scene/PoleScene.tsx'),'utf8');assert.equal(resolveBreakState(p,result),null);p.breakEnabled=true;const state=resolveBreakState(p,result);near(state.forceKN,result.timberLimitKN*2);near(state.heightM,result.timberZ);assert.equal(state.basis,'illustrative');p.loadKN=state.forceKN;assert.equal(resolveBreakState(p,result).active,true);p.breakEnabled=false;assert.equal(resolveBreakState(p,result),null);assert.doesNotMatch(scene,/upperGroup/);assert.match(scene,/Likely break zone/);assert.match(scene,/Actual break zone/);});
check('FR-013','paired observed break values override demonstration values when break mode is enabled',()=>{const p=defaultCase(),result=solvePole(p,20);p.breakEnabled=true;p.actualBreakForceKN=3;p.actualBreakHeight=.4;p.loadKN=3;assert.deepEqual(resolveBreakState(p,result),{active:true,forceKN:3,heightM:.4,basis:'observed'});});
check('FR-014','heart rot degrades stiffness, chart capacity and the timber limit',()=>{const sound=defaultCase(),base=solvePole(sound),p=defaultCase(),rot=newRegion(p,'decay'),height=1.5,dz=height-(rot.zMin+rot.zMax)/2;rot.name='Heart rot';rot.zMin+=dz;rot.zMax+=dz;rot.severity=.7;rot.shape.centreX=rot.shape.centreY=0;rot.shape.radiusX*=1.5;rot.shape.radiusY*=1.5;rot.decay={pattern:'heart',progression:'source',sourceZ:height,exponent:2,shellDepth:.03};p.regions=[rot];const local=conditionAt(p,0,0,height),section=sectionProperties(p,height),soundSection=sectionProperties(sound,height),result=solvePole(p),nearest=(rows)=>rows.reduce((a,b)=>Math.abs(b.z-height)<Math.abs(a.z-height)?b:a),profile=nearest(profileFromBasis(prepareHeightProfile(p),p.bearing,1,false)),soundProfile=nearest(profileFromBasis(prepareHeightProfile(sound),sound.bearing,1,false));assert.ok(local.e<1&&local.strength<1,'decay reduces local stiffness and strength');assert.ok(section.xx<soundSection.xx,'decay reduces section bending stiffness');assert.ok(profile.capacityApplied<soundProfile.capacityApplied,'height chart receives reduced capacity at the source');assert.ok(result.timberLimitKN<base.timberLimitKN,'decay reduces whole-pole timber capacity');assert.ok(Math.abs(result.timberZ-height)<.25,'sufficient heart rot governs near its source height');});
check('FR-015','shell rot degrades the outside fibres, chart capacity and timber limit',()=>{const sound=defaultCase(),base=solvePole(sound),p=defaultCase(),rot=newRegion(p,'decay'),height=1.5,dz=height-(rot.zMin+rot.zMax)/2;rot.name='Shell rot';rot.zMin+=dz;rot.zMax+=dz;rot.severity=.7;rot.decay={pattern:'shell',progression:'source',sourceZ:height,exponent:2,shellDepth:.03};p.regions=[rot];const R=diameterAt(p,height)/2,outer=conditionAt(p,R-.0001,0,height),inner=conditionAt(p,R-.029,0,height),core=conditionAt(p,0,0,height),section=sectionProperties(p,height),soundSection=sectionProperties(sound,height),fine=sectionProperties(p,height,320,512),result=solvePole(p),nearest=(rows)=>rows.reduce((a,b)=>Math.abs(b.z-height)<Math.abs(a.z-height)?b:a),profile=nearest(profileFromBasis(prepareHeightProfile(p),p.bearing,1,false)),soundProfile=nearest(profileFromBasis(prepareHeightProfile(sound),sound.bearing,1,false));assert.ok(outer.severity>inner.severity&&inner.severity>core.severity,'severity progresses outside inward');assert.ok(section.xx<soundSection.xx,'shell rot reduces section bending stiffness');assert.ok(Math.abs(section.xx/fine.xx-1)<.01,'production shell integration agrees with fine integration');assert.ok(profile.capacityApplied<soundProfile.capacityApplied,'height chart receives reduced shell capacity');assert.ok(result.timberLimitKN<base.timberLimitKN,'shell rot reduces whole-pole timber capacity');});

check('FR-005','both pole ends receive section-sized end-grain caps',()=>{const scene=fs.readFileSync(path.join(root,'src/scene/PoleScene.tsx'),'utf8');assert.ok(scene.includes('for (const endHeight of [top, -p.embedment])'));assert.ok(scene.includes('new T.CircleGeometry(diameterAt(p, endHeight) / 2, 64)'));assert.ok(scene.includes('stationAt(result, endHeight)'));assert.ok(scene.includes('endHeight + (endHeight === top ? 0.001 : -0.001)'));});
check('FR-003','shallow embedment is accepted and Imperial above-ground errors use feet',()=>{const p=defaultCase();p.regions=[];p.embedment=.05;assert.equal(validateCase(p).length,0);p.soil='Fixed';assert.ok(Number.isFinite(solvePole(p).tipMovement));p.embedment=0;assert.equal(validateCase(p).length,0);assert.ok(Number.isFinite(diameterAt(p,0)));assert.ok(Number.isFinite(solvePole(p).tipMovement));p.embedment=-.01;assert.ok(validateCase(p).some(e=>e.includes('non-negative')));p.unitSystem='imperial';p.embedment=p.length-.5;assert.ok(validateCase(p).some(e=>e.includes('3.28 ft above ground')));});
check('FR-003','rounded Imperial inches carry to feet without displaying 12 inches',()=>{assert.equal(formatFeetInches(.6096,2),'2.0 ft');assert.equal(formatFeetInches(.60959,2),'2.0 ft');assert.equal(formatFeetInches(-.60959,2),'-2.0 ft');assert.equal(formatFeetInches(.5969,2),'1 ft 11.50 in');assert.equal(formatPoleLength(.6096,'imperial'),'2.0 ft');});
check('FR-005','footer shows the maintained P28 build marker',()=>{assert.match(BUILD_VERSION,/^V28\.\d+$/);const app=fs.readFileSync(path.join(root,'src/ui/App.tsx'),'utf8');assert.ok(app.includes('className="build-number"'));assert.ok(app.includes('{BUILD_VERSION}</small>'));});
const failed=checks.filter(x=>!x.pass);console.log(JSON.stringify({passed:checks.length-failed.length,failed},null,2));
if(failed.length)process.exitCode=1;
