import fs from 'node:fs';
import {defaultCase} from '../../src/domain/model.ts';
import {poleMesh,endLoads,RESOLUTIONS} from '../../src/analysis/solid/mesh.ts';
import {orthotropicD,solveSolid} from '../../src/analysis/solid/kernel.ts';
import {curveMesh,curvedEndLoads,solveCurved,mappedPoint} from '../../src/analysis/solid/curved.ts';
const p=defaultCase();p.soil='Fixed';p.diameters={butt:.3,ground:.3,tip:.3};p.regions=[{id:'cavity',name:'Enclosed hollow',kind:'void',zMin:1.6,zMax:2.2,severity:1,shape:{type:'ellipse',centreX:.02,centreY:0,radiusX:.06,radiusY:.07,angle:0,profile:'rounded'},provenance:'synthetic'}];
const rows=[];for(const level of ['coarse','medium','fine']){const m=curveMesh(poleMesh(p,RESOLUTIONS[level]),p,false),end=curvedEndLoads(m,[1000,0,0],[1000*(p.length-p.embedment-m.zMax),0]),fixed=new Map(m.bottom.flatMap(n=>[0,1,2].map(k=>[n*3+k,0]))),s=solveCurved(m,orthotropicD(p.material.E),end.loads,fixed);let peak=0;for(let i=0;i<m.tets.length;i++){const z=mappedPoint(m.tets[i].map(n=>m.points[n]),[.25,.25,.25,.25]).x[2];if(z>=1.6&&z<=2.2)peak=Math.max(peak,Math.abs(s.centroidStress[i][2]));}rows.push({level,nodes:m.points.length,elements:m.tets.length,energy:s.energy,peakMPa:peak/1e6,areaError:Math.abs(end.area/(Math.PI*.15**2)-1),secondMomentError:Math.abs(end.xx/(Math.PI*.15**4/4)-1),ms:s.elapsedMs,residual:s.relativeResidual});console.log(rows.at(-1));fs.writeFileSync('verification/results/p06-refinement.json',JSON.stringify({case:p,rows,qualified:false,scope:'Curved outer pole; faceted cavity. Sampled peaks are diagnostic only.'},null,2));}
const a=rows.at(-2),b=rows.at(-1);fs.writeFileSync('verification/results/p06-refinement.json',JSON.stringify({case:p,rows,assessment:{lastEnergyChange:Math.abs(b.energy/a.energy-1),lastDiagnosticPeakChange:Math.abs(b.peakMPa/a.peakMPa-1),energyGate:.02,qualified:false,note:'Outer geometry study only. Cavity geometry, local assessment measure and boundary qualification remain open.'}},null,2));
// Attempt the fully curved cavity and retain any Jacobian rejection as a real scope limit.
try{const m=curveMesh(poleMesh(p,RESOLUTIONS.coarse),p,true),end=curvedEndLoads(m,[1000,0,0],[1000*(p.length-p.embedment-m.zMax),0]),s=solveCurved(m,orthotropicD(p.material.E),end.loads,new Map(m.bottom.flatMap(n=>[0,1,2].map(k=>[n*3+k,0]))));fs.writeFileSync('verification/results/p06-curved-cavity.json',JSON.stringify({solved:true,energy:s.energy,ms:s.elapsedMs,qualified:false},null,2));}catch(error){fs.writeFileSync('verification/results/p06-curved-cavity.json',JSON.stringify({solved:false,error:error.message,qualified:false},null,2));console.log('Curved cavity rejected: '+error.message);}
