import fs from 'node:fs';
import assert from 'node:assert/strict';
import {defaultCase,diameterAt} from '../../src/domain/model.ts';
import {sectionReferenceRadius,sideHeightAt} from '../../src/scene/sectionGeometry.ts';
import {orthotropicD,geometry,strainB,elementK} from '../../src/analysis/solid/kernel.ts';
import {poleMesh} from '../../src/analysis/solid/mesh.ts';
import {volumeRule,mappedPoint,curvedElement,curveMesh,curvedEndLoads,solveCurved} from '../../src/analysis/solid/curved.ts';
const checks=[];function check(name,ok,detail){assert.ok(ok,name+': '+detail);checks.push({name,detail});}
const p=defaultCase();check('Fixed section scale',sectionReferenceRadius(p)===.18,sectionReferenceRadius(p));
check('Tip face shrinks to half butt diameter',Math.abs(diameterAt(p,9.2)/2/sectionReferenceRadius(p)-.5)<1e-12,'ratio 0.5');
for(const h of [-1,.7,5,8])check('Taper side maps to actual height '+h,Math.abs(sideHeightAt(p,9.2,diameterAt(p,h)/2)-h)<1e-12,h);
check('No projected side at butt',sideHeightAt(p,-p.embedment,.17)===null,'null');
const pts=[[0,0,0],[1,0,0],[0,1,0],[0,0,1],[.5,0,0],[.5,.5,0],[0,.5,0],[0,0,.5],[.5,0,.5],[0,.5,.5]],D=orthotropicD(8e9),geo=geometry(pts,[0,1,2,3]);
check('Duffy quadrature volume',Math.abs(volumeRule(3).reduce((s,q)=>s+q.w,0)-1/6)<1e-14,'reference tetrahedron');
const K0=elementK(geo.inv,geo.volume,D),K1=curvedElement(pts,D).K;check('Straight geometry stiffness parity',Math.max(...K0.map((v,i)=>Math.abs(v-K1[i])))/Math.max(...K0.map(Math.abs))<1e-12,'P05 four point vs P06 64 point');
const warped=structuredClone(pts);warped[4][2]=-.04;warped[5][0]+=.03;
const A=[[.001,.002,.003],[-.002,.004,.001],[.003,.001,-.002]],u=warped.flatMap(p=>A.map(row=>row.reduce((s,v,i)=>s+v*p[i],0))),target=[.001,.004,-.002,0,.002,.006];
let strainError=0;for(const q of volumeRule(4)){const {B}=mappedPoint(warped,q.L);B.forEach((row,i)=>strainError=Math.max(strainError,Math.abs(row.reduce((s,v,k)=>s+v*u[k],0)-target[i])));}check('Curved physical affine patch',strainError<1e-13,strainError);
const k3=curvedElement(warped,D,1,4).K,k4=curvedElement(warped,D,1,5).K,difference=Math.hypot(...k3.map((v,i)=>v-k4[i]))/Math.hypot(...k4);check('Curved element quadrature sensitivity',difference<.0001,difference);
p.diameters={butt:.3,ground:.3,tip:.3};p.soil='Fixed';p.regions=[{id:'cavity',name:'Hollow',kind:'void',zMin:1.6,zMax:2.2,severity:1,shape:{type:'ellipse',centreX:.02,centreY:0,radiusX:.06,radiusY:.07,angle:0,profile:'rounded'},provenance:'synthetic'}];
const original=poleMesh(p,{angular:8,axial:4,radial:1,marginDiameters:2}),mesh=curveMesh(original,p,false),force=[1000,0,0],bending=[1000*(p.length-p.embedment-mesh.zMax),0],end=curvedEndLoads(mesh,force,bending),fixed=new Map(mesh.bottom.flatMap(n=>[0,1,2].map(k=>[n*3+k,0]))),sol=solveCurved(mesh,D,end.loads,fixed);
const resultant=[0,0,0],moment=[0,0,0];mesh.points.forEach(([x,y,z],n)=>{const [fx,fy,fz]=end.loads.slice(n*3,n*3+3);resultant[0]+=fx;resultant[1]+=fy;resultant[2]+=fz;moment[0]+=y*fz-z*fy;moment[1]+=z*fx-x*fz;moment[2]+=x*fy-y*fx;});
check('Curved face transferred force',Math.hypot(...resultant.map((v,i)=>v-force[i]))<1e-7,resultant);
check('Curved face transferred moment',Math.abs(moment[1]-1000*(p.length-p.embedment))<1e-7,moment);
check('Curved solve balance',sol.freeResidualN<1e-3,sol.freeResidualN);
const work=end.loads.reduce((s,v,i)=>s+v*sol.displacements[i],0);check('Energy/work',Math.abs(work-2*sol.energy)/work<1e-7,sol.energy);
const areaError=Math.abs(end.area/(Math.PI*.15**2)-1),momentError=Math.abs(end.xx/(Math.PI*.15**4/4)-1);check('Eight-sector curved area within 0.1%',areaError<.001,areaError);check('Eight-sector curved second moment within 0.2%',momentError<.002,momentError);
const out={case:p,mesh,D,loads:Array.from(end.loads),fixed:Array.from(fixed),solution:{u:Array.from(sol.displacements),centroidStress:sol.centroidStress,energy:sol.energy},quadratureOrder:4};fs.writeFileSync('verification/p06/reference-input.json',JSON.stringify(out));
fs.writeFileSync('verification/results/p06-checks.json',JSON.stringify({checks,areaError,momentError,elapsedMs:sol.elapsedMs,scope:'Curved outer boundary research only; P05 remains the displayed solid model.'},null,2));console.log(checks.length+' P06 checks passed; curved research solve '+sol.elapsedMs.toFixed(0)+' ms');
