import {useEffect,useRef,useState} from 'react';
/** Bearing is clockwise from north, in the direction the force acts. */
export default function Compass({bearing,onChange}:{bearing:number;onChange:(v:number)=>void}){
 const [angle,setAngle]=useState(bearing),drag=useRef(false),latest=useRef(bearing);
 useEffect(()=>{if(!drag.current)setAngle(bearing);},[bearing]);
 function update(e:React.PointerEvent<SVGSVGElement>){const r=e.currentTarget.getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=r.height/2-(e.clientY-r.top);if(Math.hypot(x,y)<4)return;latest.current=(Math.round(Math.atan2(x,y)*180/Math.PI)+360)%360;setAngle(latest.current);}
 function finish(e:React.PointerEvent<SVGSVGElement>,commit=true){if(!drag.current)return;drag.current=false;if(commit)onChange(latest.current);else setAngle(bearing);if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);}
 return <div className="load-compass"><svg viewBox="0 0 160 160" role="slider" aria-label="Load direction compass" aria-valuemin={0} aria-valuemax={359} aria-valuenow={angle} aria-valuetext={`${angle} degrees toward`} tabIndex={0} onPointerDown={e=>{if(e.button!==0)return;e.preventDefault();drag.current=true;e.currentTarget.setPointerCapture(e.pointerId);update(e);}} onPointerMove={e=>{if(drag.current)update(e);}} onPointerUp={e=>finish(e)} onPointerCancel={e=>finish(e,false)} onLostPointerCapture={e=>finish(e,false)} onKeyDown={e=>{if(e.key==='Escape'){drag.current=false;setAngle(bearing);}if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();onChange((bearing+(['ArrowRight','ArrowUp'].includes(e.key)?5:-5)+360)%360);}}}>
 <circle cx="80" cy="80" r="55" fill="white" stroke="#cbd6df"/>{Array.from({length:24},(_,i)=><line key={i} x1="80" y1="25" x2="80" y2={i%6===0?34:29} stroke="#8399a8" transform={`rotate(${i*15} 80 80)`}/>)}<text x="80" y="15">N</text><text x="148" y="84">E</text><text x="80" y="153">S</text><text x="12" y="84">W</text><g transform={`rotate(${angle} 80 80)`}><line x1="80" y1="80" x2="80" y2="38" stroke="#d92828" strokeWidth="2"/><path d="M80 29L74 42H86Z" fill="#d92828"/><circle cx="80" cy="29" r="10" fill="transparent"/></g><circle cx="80" cy="80" r="3" fill="#54768b"/></svg><span>{angle}° toward</span></div>;
}
