import {useEffect,useState} from 'react';
import {diameterAt,newRegion,clamp} from '../domain/model.ts';
import type {PoleCase,Region} from '../domain/model.ts';
export type DefectPreset='heart'|'shell'|'incipient'|'void'|'knot'|'drilling';
export function presetRegion(p:PoleCase,preset:DefectPreset){
  const r=newRegion(p,['void','knot','drilling'].includes(preset)?preset as Region['kind']:'decay');
  if(r.kind==='decay'){r.name=preset==='shell'?'Shell rot':preset==='incipient'?'Incipient heart rot':'Heart rot';r.severity=preset==='incipient'?.2:.7;r.decay={pattern:preset==='shell'?'shell':'heart',progression:'source',sourceZ:(r.zMin+r.zMax)/2,exponent:2,shellDepth:.03};if(r.shape.type==='ellipse'&&preset!=='shell'){r.shape.centreX=0;r.shape.centreY=0;}}
  return r;
}
function Field({label,value,unit,min,max,step=.01,onChange}:{label:string;value:number;unit:string;min?:number;max?:number;step?:number;onChange:(v:number)=>void}){
  const [draft,setDraft]=useState(String(value));useEffect(()=>setDraft(String(Number(value.toFixed(4)))),[value]);
  const commit=()=>{const v=Number(draft);if(draft.trim()&&Number.isFinite(v))onChange(clamp(v,min??-Infinity,max??Infinity));else setDraft(String(value));};
  return <label className="number-field"><span>{label}</span><div><input type="number" aria-label={label} value={draft} min={min} max={max} step={step} onChange={e=>setDraft(e.target.value)} onBlur={commit} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();}}/><small>{unit}</small></div></label>;
}
export default function DefectEditor({pole,selected,onSelect,onAdd,onEdit,onRemove,onFocus}:{pole:PoleCase;selected:string|null;onSelect:(r:Region)=>void;onAdd:(preset:DefectPreset)=>void;onEdit:(id:string,update:Partial<Region>)=>void;onRemove:(id:string)=>void;onFocus:()=>void}){
  const [expanded,setExpanded]=useState<string|null>(selected),[preset,setPreset]=useState<DefectPreset>('heart');useEffect(()=>{if(selected)setExpanded(selected);},[selected]);
  return <div className="defect-editor"><div className="defect-add"><select aria-label="New defect type" value={preset} onChange={e=>setPreset(e.target.value as DefectPreset)}><option value="heart">Heart rot</option><option value="shell">Shell rot</option><option value="incipient">Incipient decay</option><option value="void">Cavity</option><option value="knot">Knot</option><option value="drilling">Drilling</option></select><button className="small-button" onClick={()=>onAdd(preset)}>Add</button></div>
    {!pole.regions.length&&<p className="field-note">Choose a defect to explore its effect on the pole.</p>}
    {pole.regions.map(r=>{const open=expanded===r.id,centre=(r.zMin+r.zMax)/2,update=(v:Partial<Region>)=>onEdit(r.id,v),sh=r.shape,drill=r.drilling;
      const shape=(v:Record<string,number>)=>sh.type!=='section-contours'&&update({shape:{...sh,...v}});
      const move=(z:number)=>{const dz=z-centre;update({zMin:r.zMin+dz,zMax:r.zMax+dz,...(r.decay?{decay:{...r.decay,sourceZ:r.decay.sourceZ+dz}}:{})});};
      const decay=r.decay??{pattern:'heart' as const,progression:'uniform' as const,sourceZ:centre,exponent:2,shellDepth:.03};
      return <section className="defect-card" key={r.id}><button className="defect-card-heading" aria-expanded={open} onClick={()=>{setExpanded(open?null:r.id);if(!open)onSelect(r);}}><strong>{r.name}</strong><span>{centre.toFixed(2)} m · {open?'Hide':'Edit'}</span></button>{open&&<div className="defect-card-body">
        <Field label="Defect height" value={centre} unit="m" min={-pole.embedment+(r.zMax-r.zMin)/2} max={pole.length-pole.embedment-(r.zMax-r.zMin)/2} onChange={move}/>
        {r.kind==='drilling'&&drill?<><label className="select-field">Drill diameter<select aria-label="Drill diameter" value={drill.diameter} onChange={e=>{const diameter=Number(e.target.value);update({drilling:{...drill,diameter},zMin:centre-diameter/2,zMax:centre+diameter/2});}}><option value={.009525}>3/8 in · 9.525 mm</option><option value={.0111125}>7/16 in · 11.113 mm</option><option value={.0127}>1/2 in · 12.7 mm</option></select></label><div className="field-grid"><Field label="Drill depth" value={drill.depth*1000} unit="mm" min={1} max={diameterAt(pole,centre)*1000} step={1} onChange={v=>update({drilling:{...drill,depth:v/1000}})}/><Field label="Drill bearing" value={drill.bearing} unit="°" min={0} max={359} step={5} onChange={v=>update({drilling:{...drill,bearing:v}})}/></div><button className="link-button" onClick={()=>update({drilling:{...drill,depth:diameterAt(pole,centre)/3}})}>Set depth to ⅓ diameter</button></>:<>
          <Field label="Defect length" value={r.zMax-r.zMin} unit="m" min={.02} max={Math.min(centre+pole.embedment,pole.length-pole.embedment-centre)*2} onChange={v=>update({zMin:centre-v/2,zMax:centre+v/2,...(r.decay?{decay:{...r.decay,sourceZ:clamp(r.decay.sourceZ,centre-v/2,centre+v/2)}}:{})})}/>
          {r.kind==='decay'&&<><label className="select-field">Decay pattern<select aria-label="Decay pattern" value={decay.pattern} onChange={e=>update({name:e.target.value==='shell'?'Shell rot':'Heart rot',decay:{...decay,pattern:e.target.value as 'heart'|'shell'}})}><option value="heart">Heart rot · inside outward</option><option value="shell">Shell rot · outside inward</option></select></label><Field label="Severity at source" value={r.severity*100} unit="%" min={0} max={100} step={5} onChange={v=>update({severity:v/100})}/></>}
          {r.kind==='decay'&&decay.pattern==='shell'?<Field label="Shell decay depth" value={decay.shellDepth*1000} unit="mm" min={1} max={diameterAt(pole,centre)*500} step={2} onChange={v=>update({decay:{...decay,shellDepth:v/1000}})}/>:sh.type!=='section-contours'&&<div className="field-grid"><Field label="Defect width" value={sh.radiusX*2000} unit="mm" min={5} max={diameterAt(pole,centre)*1500} step={5} onChange={v=>shape({radiusX:v/2000})}/><Field label="Defect depth" value={sh.radiusY*2000} unit="mm" min={5} max={diameterAt(pole,centre)*1500} step={5} onChange={v=>shape({radiusY:v/2000})}/></div>}
          {r.kind==='knot'&&<><Field label="Knot grain angle" value={r.knot?.grainAngle??45} unit="°" min={0} max={90} step={5} onChange={v=>update({knot:{grainAngle:v}})}/><p className="field-note">Grain angle changes local stiffness and strength in the beam. Illustrative approximation; splitting is not assessed.</p></>}
          {sh.type!=='section-contours'&&decay.pattern!=='shell'&&<details className="advanced"><summary>Position & shape</summary><div className="field-grid"><Field label="East–west offset" value={sh.centreX*1000} unit="mm" step={2} onChange={v=>shape({centreX:v/1000})}/><Field label="North–south offset" value={sh.centreY*1000} unit="mm" step={2} onChange={v=>shape({centreY:v/1000})}/></div><Field label="Shape rotation" value={sh.angle} unit="°" min={0} max={180} step={5} onChange={v=>shape({angle:v})}/></details>}
          {r.kind==='decay'&&decay.pattern==='shell'&&<details className="advanced"><summary>Position</summary><Field label="Shell east–west offset" value={(r.decay?.offsetX??0)*1000} unit="mm" step={2} onChange={v=>update({decay:{...decay,offsetX:v/1000}})}/><Field label="Shell north–south offset" value={(r.decay?.offsetY??0)*1000} unit="mm" step={2} onChange={v=>update({decay:{...decay,offsetY:v/1000}})}/></details>}{r.kind==='decay'&&<details className="advanced"><summary>Decay spread</summary><label className="select-field">Progression<select aria-label="Decay progression" value={decay.progression} onChange={e=>update({decay:{...decay,progression:e.target.value as 'source'|'uniform'}})}><option value="source">Diminish away from source</option><option value="uniform">Uniform within region</option></select></label>{decay.progression==='source'&&<><Field label="Decay source height" value={decay.sourceZ} unit="m" min={r.zMin} max={r.zMax} onChange={v=>update({decay:{...decay,sourceZ:v}})}/><Field label="Spread exponent" value={decay.exponent} unit="" min={.5} max={6} step={.25} onChange={v=>update({decay:{...decay,exponent:v}})}/></>}<p className="field-note">Assumed spatial progression. Early decay may have little visible discoloration in Setup; Defects makes its prescribed extent visible.</p></details>}
        </>}
        <div className="defect-card-actions"><button onClick={()=>{onSelect(r);onFocus();}}>Focus</button><button onClick={()=>onRemove(r.id)}>Remove</button></div>
      </div>}</section>;
    })}
  </div>;
}
