import type {WaveControl} from '../inspection/mockupProtocol.ts';
import SignalEnvelope from './SignalEnvelope.tsx';
import type {AnalysisResult} from '../analysis/beam.ts';
import TestReadout from './TestReadout.tsx';
import {forwardRef,useEffect,useImperativeHandle,useRef,useState} from 'react';
import {clamp,type PoleCase} from '../domain/model.ts';
import type {WaveSequence} from '../inspection/waveSimulation.ts';
import {paintProbePair} from '../scene/inspectionProbes.ts';
import type {SectionPreviewHandle} from './SectionView.tsx';
const sequences=new Map<string,WaveSequence>();let cacheBytes=0;
function remember(key:string,data:WaveSequence){const size=data.field.byteLength;cacheBytes-=sequences.get(key)?.field.byteLength??0;sequences.set(key,data);cacheBytes+=size;while(cacheBytes>24*1024*1024&&sequences.size>1){const oldest=sequences.keys().next().value!;cacheBytes-=sequences.get(oldest)!.field.byteLength;sequences.delete(oldest);}}
// Magnitude palette, common source/reference normalisation at every frame.
const stops=[[0,9,15,73],[.18,15,45,156],[.38,0,141,227],[.58,15,198,168],[.74,184,226,66],[.88,255,201,37],[1,230,52,33]];
export const wavePalette=Array.from({length:256},(_,i)=>{const t=i/255,hi=stops.findIndex(s=>s[0]>=t),a=stops[Math.max(0,hi-1)],b=stops[Math.max(0,hi)],f=b[0]===a[0]?0:(t-a[0])/(b[0]-a[0]);return [1,2,3].map(k=>Math.round(a[k]+f*(b[k]-a[k])));});
interface Props {control?:WaveControl|null;result?:AnalysisResult|null;capture?:boolean;pole:PoleCase;z:number;bearing:number;onBearing:(v:number)=>void;onHeight:(v:number)=>void}
export default forwardRef<SectionPreviewHandle,Props>(function DetectSection({control=null,result=null,capture=false,pole,z,bearing,onBearing,onHeight},ref){
 const [sequence,setSequence]=useState<WaveSequence|null>(null),[pending,setPending]=useState(true),[progress,setProgress]=useState(0),[error,setError]=useState(''),[playing,setPlaying]=useState(()=>capture||!matchMedia('(prefers-reduced-motion: reduce)').matches),[speed,setSpeed]=useState(2),[reference,setReference]=useState(true),[outlines,setOutlines]=useState(true),[detail,setDetail]=useState('auto'),[preview,setPreview]=useState<number|null>(null);
 const effectivePlaying=control?control.running:playing;
 const lastRun=useRef('');
 useEffect(()=>{if(control?.running&&control.runId!==lastRun.current){lastRun.current=control.runId;position.current=0;last.current=0;lastPaint.current='';}},[control?.running,control?.runId]);
 const lastPaint=useRef(''),paintedRadius=useRef(140),envelopePlayhead=useRef<SVGLineElement>(null);
 const canvas=useRef<HTMLCanvasElement>(null),trace=useRef<HTMLCanvasElement>(null),timeLabel=useRef<HTMLSpanElement>(null),timeline=useRef<HTMLInputElement>(null),position=useRef(0),last=useRef(0),raf=useRef(0),draw=useRef<()=>void>(()=>{}),tile=useRef<HTMLCanvasElement|null>(null),pixels=useRef<ImageData|null>(null),contours=useRef<HTMLCanvasElement|null>(null),drag=useRef<{start:number;offset:number;angle:number}|null>(null),wheelTimer=useRef<ReturnType<typeof setTimeout>|null>(null),requestedHeight=useRef(z);
 const n=detail==='fine'?192:window.innerWidth<=760||navigator.hardwareConcurrency<=4?96:128,key=JSON.stringify({length:pole.length,embedment:pole.embedment,diameters:pole.diameters,regions:pole.regions,z,bearing,n});
 useImperativeHandle(ref,()=>({preview(value){setPreview(value);}}));
 useEffect(()=>{requestedHeight.current=z;setPreview(null);setPending(true);setError('');setProgress(0);last.current=0;const cached=sequences.get(key);if(cached){setSequence(cached);setPending(false);position.current=0;return;}let cancelled=false,worker:Worker|null=null;
  const timer=setTimeout(()=>{worker=new Worker(new URL('../workers/wave.worker.ts',import.meta.url),{type:'module'});worker.onmessage=e=>{if(cancelled)return;if(e.data.progress!==undefined){setProgress(e.data.progress);return;}if(e.data.error){setError(e.data.error);setPending(false);}else{remember(key,e.data.result);setSequence(e.data.result);setPending(false);position.current=0;}worker?.terminate();};worker.onerror=()=>{if(!cancelled){setError('Wave calculation unavailable. Try another section.');setPending(false);}worker?.terminate();};worker.postMessage({pole,z,bearing,n});},180);
  return()=>{cancelled=true;clearTimeout(timer);worker?.terminate();};
 },[key]);
 useEffect(()=>{lastPaint.current='';if(!sequence)return;const el=document.createElement('canvas');el.width=el.height=sequence.n;tile.current=el;pixels.current=new ImageData(sequence.n,sequence.n);const edge=document.createElement('canvas');edge.width=edge.height=sequence.n;const c=edge.getContext('2d')!,im=c.createImageData(sequence.n,sequence.n);
  for(let y=1;y<sequence.n-1;y++)for(let x=1;x<sequence.n-1;x++){const i=y*sequence.n+x;if(sequence.mask[i]===0)continue;const boundary=[i-1,i+1,i-sequence.n,i+sequence.n].some(j=>sequence.mask[i]!==sequence.mask[j]||Math.abs(sequence.condition[i]-sequence.condition[j])>18);if(boundary){im.data.set([220,233,247,150],i*4);}}
  c.putImageData(im,0,0);contours.current=edge;
 },[sequence]);
 draw.current=()=>{const el=canvas.current,s=sequence;if(!el||!el.offsetWidth||(!capture&&document.hidden))return;const signature=[position.current.toFixed(5),outlines,reference,drag.current?.angle].join('|');if(s&&lastPaint.current===signature)return;lastPaint.current=signature;if(s){const R=s.dx*(s.n-4)/2,a=(drag.current?.angle??s.bearing)*Math.PI/180,v=Math.max(R,Math.abs(Math.cos(a))*(R+.16)+.03),sc=Math.min(512*.46/(R+.18),168/v),height=Math.ceil(2*(v*sc+28));if(el.height!==height)el.height=height;}const c=el.getContext('2d')!,size=512;c.clearRect(0,0,size,el.height);if(!s||!tile.current||!pixels.current){c.fillStyle='#101b48';c.beginPath();c.arc(256,200,140,0,Math.PI*2);c.fill();return;}
  const R=s.dx*(s.n-4)/2,angle=(drag.current?.angle??s.bearing)*Math.PI/180,vertical=Math.max(R,Math.abs(Math.cos(angle))*(R+.16)+.03),scale=Math.min(size*.46/(R+.18),168/vertical),r=R*scale,t=clamp(position.current,0,1),f=t*(s.frames-1),lo=Math.floor(f),hi=Math.min(s.frames-1,lo+1),mix=f-lo,nn=s.n*s.n,im=pixels.current;
  paintedRadius.current=r;c.save();c.translate(0,el.height/2-256);
  for(let i=0;i<nn;i++){const offset=i*4;if(!s.mask[i]){im.data[offset+3]=0;continue;}const rgb=s.mask[i]===2?[19,25,41]:wavePalette[Math.round(s.field[lo*nn+i]*(1-mix)+s.field[hi*nn+i]*mix)];im.data[offset]=rgb[0];im.data[offset+1]=rgb[1];im.data[offset+2]=rgb[2];im.data[offset+3]=255;}
  tile.current.getContext('2d')!.putImageData(im,0,0);const extent=s.n*s.dx*scale;c.save();c.beginPath();c.arc(256,256,r,0,Math.PI*2);c.clip();c.imageSmoothingEnabled=true;c.drawImage(tile.current,256-extent/2,256-extent/2,extent,extent);if(outlines&&contours.current)c.drawImage(contours.current,256-extent/2,256-extent/2,extent,extent);c.restore();c.strokeStyle='#455975';c.lineWidth=1.3;c.beginPath();c.arc(256,256,r,0,Math.PI*2);c.stroke();
  paintProbePair(c,R,scale,drag.current?.angle??s.bearing);
  c.font='12px system-ui';c.fillStyle='#526c81';c.textAlign='center';c.fillText('N',256+(Math.abs(Math.cos(angle))>.85?35:0),256-r-12);const a=(drag.current?.angle??s.bearing)*Math.PI/180;for(const sign of [1,-1]){const rr=(R+.095)*scale;c.fillText(sign===1?'Transmit':'Receive',256+sign*Math.sin(a)*rr+Math.cos(a)*50,256-sign*Math.cos(a)*rr+Math.sin(a)*50+4);}
  c.restore();
  if(timeLabel.current)timeLabel.current.textContent=`${Math.round(t*s.duration*1e6)} µs`;if(timeline.current)timeline.current.value=String(t*1000);if(envelopePlayhead.current){const px=String(60+t*436);envelopePlayhead.current.setAttribute('x1',px);envelopePlayhead.current.setAttribute('x2',px);}el.dataset.frame=String(lo);el.dataset.height=String(s.height);el.dataset.bearing=String(s.bearing);
  const tc=trace.current?.getContext('2d');if(tc){const w=512,h=112;tc.clearRect(0,0,w,h);tc.strokeStyle='#e5ebf0';tc.lineWidth=1;for(const y of [28,56,84]){tc.beginPath();tc.moveTo(0,y);tc.lineTo(w,y);tc.stroke();}const peak=Math.max(1e-20,...s.reference.map(Math.abs),...s.trace.map(Math.abs));
   for(const [values,colour,dash] of [[s.reference,'#9caebc',true],[s.trace,'#176faf',false]] as const){if(dash&&!reference)continue;tc.strokeStyle=colour;tc.lineWidth=dash?1.5:2;tc.setLineDash(dash?[5,4]:[]);tc.beginPath();for(let i=0;i<values.length;i++){const x=i/(values.length-1)*w,y=56-values[i]/peak*45;i?tc.lineTo(x,y):tc.moveTo(x,y);}tc.stroke();}tc.setLineDash([]);tc.strokeStyle='#ec853a';tc.beginPath();tc.moveTo(t*w,0);tc.lineTo(t*w,h);tc.stroke();}
 };
 useEffect(()=>{let disposed=false;function tick(now:number){if(disposed)return;const dt=last.current?Math.min(.1,(now-last.current)/1000):0;last.current=now;if(effectivePlaying&&!pending&&!error&&!drag.current&&preview===null&&(capture||!document.hidden)){position.current+=dt/(8/speed);if(position.current>1.06)position.current=0;}draw.current();raf.current=requestAnimationFrame(tick);}raf.current=requestAnimationFrame(tick);return()=>{disposed=true;cancelAnimationFrame(raf.current);};},[effectivePlaying,speed,pending,error,preview,capture]);
 useEffect(()=>{const el=canvas.current;if(!el)return;const wheel=(e:WheelEvent)=>{e.preventDefault();requestedHeight.current=clamp(requestedHeight.current-e.deltaY*(e.deltaMode===1?16:1)*.002,0,pole.length-pole.embedment);setPreview(requestedHeight.current);if(wheelTimer.current)clearTimeout(wheelTimer.current);wheelTimer.current=setTimeout(()=>onHeight(requestedHeight.current),150);};el.addEventListener('wheel',wheel,{passive:false});return()=>{el.removeEventListener('wheel',wheel);if(wheelTimer.current)clearTimeout(wheelTimer.current);};},[pole.length,pole.embedment,onHeight]);
 function move(e:React.PointerEvent<HTMLCanvasElement>){if(!drag.current)return;const box=e.currentTarget.getBoundingClientRect(),a=Math.atan2(e.clientX-box.left-box.width/2,box.height/2-(e.clientY-box.top))*180/Math.PI;drag.current.angle=(a-drag.current.offset+360)%360;}
 function finish(e:React.PointerEvent<HTMLCanvasElement>,commit:boolean){if(!drag.current)return;const d=drag.current;drag.current=null;if(commit)onBearing(Math.round(d.angle)%360);if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);}
 const stale=!!sequence&&(sequence.height!==z||sequence.bearing!==bearing||pending||!!error||preview!==null);
 return <section className="detect-wave" data-playback={effectivePlaying?'running':'paused'} data-controller={control?'inspection-app':'local'}><div className="detect-heading"><div><span>UB1000 · Detect</span><h3>Ultrasound through the section</h3></div><span ref={timeLabel}>0 µs</span></div><div className="wave-status" role="status">{error||preview!==null?error||`Positioning at ${preview!.toFixed(2)} m · release to calculate`:pending?`Calculating wave response… ${Math.round(progress*100)}%`:`Section ${z.toFixed(2)} m · ${bearing}° · simulated response`}{stale&&sequence&&<small>Showing previous calculation at {sequence.height.toFixed(2)} m / {sequence.bearing}°</small>}</div>
 <canvas ref={canvas} width={512} height={400} className="wave-field" aria-label="Animated ultrasound displacement through the selected pole section" tabIndex={0} onPointerDown={e=>{if(e.button!==0||!sequence)return;const box=e.currentTarget.getBoundingClientRect(),x=e.clientX-box.left-box.width/2,y=box.height/2-(e.clientY-box.top),r=paintedRadius.current/512*box.width;if(Math.hypot(x,y)<r)return;drag.current={start:bearing,offset:Math.atan2(x,y)*180/Math.PI-bearing,angle:bearing};e.currentTarget.setPointerCapture(e.pointerId);e.preventDefault();}} onPointerMove={move} onPointerUp={e=>finish(e,true)} onPointerCancel={e=>finish(e,false)} onLostPointerCapture={e=>finish(e,false)} onKeyDown={e=>{if(e.key==='Escape')drag.current=null;if(e.key==='ArrowUp'||e.key==='ArrowDown'){e.preventDefault();onHeight(clamp(z+(e.key==='ArrowUp'?.05:-.05),0,pole.length-pole.embedment));}if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();onBearing((bearing+(e.key==='ArrowRight'?5:-5)+360)%360);}}}/>
 <TestReadout pole={pole} z={z} result={result}/>{control&&<p className="wave-app-control">{control.running?'Scanning in the inspection app':'Start a scan in the inspection app to play the waves'}</p>}<details className="wave-tools" onToggle={()=>{lastPaint.current='';}}><summary>Wave controls and received signal</summary><div className="wave-legend"><i/><span>Low displacement</span><span>High · fixed reference scale</span></div><div className="wave-playback"><button disabled={!!control} onClick={()=>setPlaying(!playing)}>{effectivePlaying?'Pause':'Play'}</button><button disabled={!!control} onClick={()=>{position.current=0;setPlaying(true);}}>Replay</button><select aria-label="Wave playback speed" value={speed} onChange={e=>setSpeed(Number(e.target.value))}><option value={1}>1×</option><option value={2}>2×</option><option value={4}>4×</option></select><select aria-label="Wave detail" value={detail} onChange={e=>setDetail(e.target.value)}><option value="auto">Auto detail</option><option value="fine">Fine detail</option></select></div><input disabled={!!control} className="wave-timeline" aria-label="Wave animation time" type="range" min={0} max={1000} defaultValue={0} ref={timeline} onChange={e=>{position.current=Number(e.target.value)/1000;setPlaying(false);}}/>
 <div className="wave-signal-title"><strong>Received signal</strong><label><input type="checkbox" checked={reference} onChange={e=>setReference(e.target.checked)}/>Sound reference</label></div><canvas ref={trace} width={512} height={112} className="wave-trace" aria-label="Received displacement compared with sound timber using the same signal scale"/><div className="wave-trace-labels"><span>0 µs</span><span>{sequence?Math.round(sequence.duration*1e6):'—'} µs</span></div><SignalEnvelope sequence={sequence} showReference={reference} stale={stale} playhead={envelopePlayhead}/><label className="wave-outline"><input type="checkbox" checked={outlines} onChange={e=>setOutlines(e.target.checked)}/>Defect boundaries</label>
 <details className="wave-basis"><summary>Simulation basis</summary><p>Illustrative 2D elastic waves: compression, shear, boundary reflections and material absorption. This is not a measured UB1000 signal. Blue: this section; grey: the same sound pole. Both use the same pulse and signal scale.</p><p>Default playback is a four-second loop (2× an eight-second teaching cycle). Original animation timing was unavailable. The colour response uses a fixed square-root amplitude scale referenced to sound timber.</p>{sequence&&<><p>{sequence.n} × {sequence.n} grid · {(sequence.frequency/1000).toFixed(1)} kHz illustrative pulse · {(sequence.elapsedMs/1000).toFixed(2)} s calculation. Received peak: {(sequence.peakRatio*100).toFixed(0)}% of sound reference. Interference can raise local peaks; this is not a strength percentage.</p>{sequence.warnings.map(w=><p key={w}>{w}</p>)}</>}</details></details></section>;
});
