import {paintProbePair} from '../scene/inspectionProbes.ts';
import SectionSketch,{SketchToolbar,type SketchProps} from './SectionSketch.tsx';
import type {SolidField} from '../analysis/solid/field.ts';
import {displayedStress,inLocalZone} from '../analysis/solid/field.ts';
import {forwardRef,useEffect,useImperativeHandle,useRef,useState} from 'react';
import type {PoleCase,ViewMode,StressDisplay} from '../domain/model.ts';
import {conditionAt,diameterAt,clamp} from '../domain/model.ts';
import type {AnalysisResult} from '../analysis/beam.ts';
import {stationAt} from '../analysis/beam.ts';
import {withPhoto} from '../scene/materials.ts';
import {paintTaperedSection} from '../scene/taperedSection.ts';
import {sectionReferenceRadius,sideHeightAt} from '../scene/sectionGeometry.ts';
import {SectionCache} from '../scene/sectionCache.ts';
import {PROBE_OUTER_REACH} from '../inspection/placeholder.ts';
import {displayStress,formatPoleLength,formatSmallLength,unitLabels,type UnitSystem} from '../domain/units.ts';
export interface SectionPreviewHandle {preview:(height:number|null)=>void}
interface Props extends Omit<SketchProps,'zoom'> {units?:UnitSystem;testBearing?:number;onTestBearing?:(bearing:number)=>void;utilisationMax?:number;onHeight:(z:number)=>void;pole:PoleCase;z:number;view:ViewMode;result:AnalysisResult|null;solid?:SolidField|null;scan?:boolean;stressDisplay?:StressDisplay}
export default forwardRef<SectionPreviewHandle,Props>(function SectionView({units='metric',testBearing,onTestBearing,utilisationMax=1.5,onHeight,pole,z,view,result,solid,scan=false,stressDisplay='stress',selected,onAdd,onEdit,onSelect,onMessage},ref){
 const testDrag=useRef<number|null>(null),testStart=useRef(0);
 const [drawing,setDrawing]=useState(false),[sketchKind,setSketchKind]=useState<'void'|'decay'>('void');
 const wrap=useRef<HTMLDivElement>(null),heightState=useRef({z,pole,onHeight,testBearing}),wheelTimer=useRef<ReturnType<typeof setTimeout>|null>(null);heightState.current={z,pole,onHeight,testBearing};
 const canvas=useRef<HTMLCanvasElement>(null),diameter=useRef<HTMLSpanElement>(null),status=useRef<HTMLSpanElement>(null),[probe,setProbe]=useState('Move over the section to inspect');
 const sampler=useRef<Worker|null>(null),busy=useRef(false),wanted=useRef<{z:number;size:number}|null>(null),cache=useRef(new SectionCache<HTMLCanvasElement>()),samplerError=useRef(''),requestSample=useRef<()=>void>(()=>{}),prefetch=useRef<number[]>([]),requested=useRef(new Set<string>());
 const displayed=useRef<number|null>(null),displayedView=useRef(view);
 const zoom=useRef(1),live=useRef<number|null>(null),frame=useRef(0),photos=useRef<Record<string,HTMLImageElement|undefined>>({}),draw=useRef<()=>void>(()=>{}),lastPaint=useRef('');
 const schedule=()=>{if(!frame.current)frame.current=requestAnimationFrame(()=>draw.current());};
 draw.current=()=>{frame.current=0;const el=canvas.current;if(!el)return;const height=clamp(live.current??z,-pole.embedment,pole.length-pole.embedment),started=performance.now(),size=512;if(testBearing!==undefined)zoom.current=sectionReferenceRadius(pole)/(diameterAt(pole,height)/2+PROBE_OUTER_REACH+.02);const cutSize=Math.min(1024,Math.max(256,Math.round(size*diameterAt(pole,height)/2/sectionReferenceRadius(pole)*zoom.current/64)*64));
  const next={z:height,size:cutSize};if(wanted.current?.z!==height||wanted.current.size!==cutSize){wanted.current=next;prefetch.current=[];for(let i=1;i<=8;i++)for(const sign of [1,-1])prefetch.current.push(clamp(Math.round((height+sign*i*.01)*100)/100,-pole.embedment,pole.length-pole.embedment));}
  const hit=cache.current.get(height,cutSize),ready=!!hit;
  if(!ready&&displayed.current!==null){if(status.current)status.current.textContent=samplerError.current||`Updating ${view==='Innerview'?'Defects':view} · showing ${displayedView.current==='Innerview'?'Defects':displayedView.current} at ${formatPoleLength(displayed.current,units)}`;el.dataset.heldFrames=String(Number(el.dataset.heldFrames??0)+1);el.dataset.sectionReady='false';el.dataset.requestedHeight=String(height);lastPaint.current=cache.current.key(height,cutSize);requestSample.current();return;}
  let cut=hit;if(!cut){cut=document.createElement('canvas');cut.width=cut.height=64;const ctx=cut.getContext('2d')!;ctx.fillStyle='#e9edef';ctx.beginPath();ctx.arc(32,32,64*.46,0,Math.PI*2);ctx.fill();}
  if(el.width!==size)el.width=el.height=size;paintTaperedSection(el,pole,height,view,result,stressDisplay,photos.current.end,photos.current.wood,solid,false,undefined,cut,false,zoom.current);
  if(testBearing!==undefined)paintProbePair(el.getContext('2d')!,diameterAt(pole,height)/2,size*.46/sectionReferenceRadius(pole)*zoom.current,testBearing);
  if(ready){displayed.current=height;displayedView.current=view;}
  el.setAttribute('aria-label',(view==='Innerview'?'Defects':view)+' cross-section at '+height.toFixed(2)+' metres relative to groundline');el.dataset.renderHeight=String(height);el.dataset.paintMs=(performance.now()-started).toFixed(1);el.dataset.resolution=String(size);el.dataset.cacheFrames=String(cache.current.count);el.dataset.cacheBytes=String(cache.current.bytes);el.dataset.sectionReady=String(ready);el.dataset.editReady=String(ready&&live.current===null);if(live.current!==null)el.dataset.previewFrames=String(Number(el.dataset.previewFrames??0)+1);
  if(diameter.current)diameter.current.textContent='Ø '+formatSmallLength(diameterAt(pole,height),units,units==='metric'?0:2);
  if(status.current)status.current.textContent=samplerError.current||(ready?'':view==='Stresses'&&!result?'Stress calculation pending':'Preparing section…');lastPaint.current=cache.current.key(height,cutSize);requestSample.current();
 };
 requestSample.current=()=>{if(!sampler.current||busy.current||!wanted.current||samplerError.current)return;const w=wanted.current;let height:number|undefined;
  if(!cache.current.has(w.z,w.size))height=w.z;else while(prefetch.current.length){const candidate=prefetch.current.shift()!,key=cache.current.key(candidate,w.size);if(!cache.current.has(candidate,w.size)&&!requested.current.has(key)){height=candidate;break;}}
  if(height===undefined)return;busy.current=true;requested.current.add(cache.current.key(height,w.size));sampler.current.postMessage({kind:'paint',z:height,size:w.size,id:1});
 };
 const renderKey=JSON.stringify(view==='Stresses'?pole:{...pole,loadKN:0,bearing:0}),renderResult=view==='Stresses'?result:null,renderSolid=view==='Stresses'?solid:null;
 useEffect(()=>{cache.current.clear();requested.current.clear();busy.current=false;wanted.current=null;samplerError.current='';const worker=new Worker(new URL('../workers/section.worker.ts',import.meta.url),{type:'module'});sampler.current=worker;
  worker.postMessage({kind:'configure',utilisationMax,pole,result,solid,view,display:stressDisplay,photoURL:new URL(import.meta.env.BASE_URL+'textures/endgrain-p08.png',location.href).href,atlasURL:new URL(import.meta.env.BASE_URL+'textures/defects-p08.png',location.href).href});
  worker.onmessage=e=>{if(sampler.current!==worker)return;busy.current=false;const data=e.data;if(data.error){samplerError.current='Section unavailable';schedule();return;}const image=document.createElement('canvas');image.width=image.height=data.size;image.getContext('2d')!.putImageData(new ImageData(data.pixels,data.size,data.size),0,0);cache.current.put(data.z,data.size,image);if(lastPaint.current===cache.current.key(data.z,data.size))schedule();requestSample.current();};
  worker.onerror=()=>{busy.current=false;samplerError.current='Section unavailable';schedule();};schedule();return()=>{worker.terminate();if(sampler.current===worker)sampler.current=null;};
 },[renderKey,view,renderResult,renderSolid,stressDisplay,utilisationMax]);
 useEffect(()=>{const el=wrap.current;if(!el)return;const wheel=(e:WheelEvent)=>{e.preventDefault();const q=heightState.current,delta=e.deltaY*(e.deltaMode===1?16:e.deltaMode===2?300:1);live.current=clamp((live.current??q.z)-delta*.002,q.testBearing!==undefined?0:-q.pole.embedment,q.pole.length-q.pole.embedment);schedule();if(wheelTimer.current)clearTimeout(wheelTimer.current);wheelTimer.current=setTimeout(()=>{if(live.current!==null)heightState.current.onHeight(live.current);},100);};el.addEventListener('wheel',wheel,{passive:false});return()=>{el.removeEventListener('wheel',wheel);if(wheelTimer.current)clearTimeout(wheelTimer.current);};},[]);
 useEffect(()=>{const cancel=(e:KeyboardEvent)=>{if(e.key==='Escape')setDrawing(false);};window.addEventListener('keydown',cancel);return()=>window.removeEventListener('keydown',cancel);},[]);
 useImperativeHandle(ref,()=>({preview(height){live.current=height;schedule();}}));
 useEffect(()=>{const stops=[['end','textures/endgrain-p08.png'],['wood','textures/treated-pine-p02.png']].map(([key,path])=>withPhoto(path,img=>{photos.current[key]=img;schedule();}));return()=>{stops.forEach(stop=>stop());cancelAnimationFrame(frame.current);};},[]);
 useEffect(()=>{setDrawing(false);},[view]);
 useEffect(()=>{live.current=null;setProbe('Move over the section to inspect');schedule();},[pole,z,view,result,stressDisplay,solid,testBearing]);
 useEffect(()=>{if(testBearing===undefined){zoom.current=1;schedule();}},[testBearing===undefined]);
 function inspect(e:React.PointerEvent<HTMLCanvasElement>){if(testDrag.current!==null&&testBearing!==undefined){const box=e.currentTarget.getBoundingClientRect(),a=(Math.atan2(e.clientX-box.left-box.width/2,box.height/2-(e.clientY-box.top))*180/Math.PI+360)%360;onTestBearing?.((a-testDrag.current+360)%360);return;}const height=displayed.current??z,r=e.currentTarget.getBoundingClientRect(),R=diameterAt(pole,height)/2,reference=sectionReferenceRadius(pole)/zoom.current,x=((e.clientX-r.left)/r.width-.5)*reference/.46,y=(.5-(e.clientY-r.top)/r.height)*reference/.46;
  if(Math.hypot(x,y)>R){const side=sideHeightAt(pole,height,Math.hypot(x,y));setProbe(side!==null?'Pole exterior below cut · '+formatPoleLength(side,units):'Move over the section to inspect');return;}
  const c=conditionAt(pole,x,y,height);if(view==='Stresses'&&result){const stress=displayedStress(pole,stationAt(result,height),x,y,height,stressDisplay==='utilisation'?'stress':stressDisplay,solid);setProbe(stress===null?(c.voided?'No timber':'Outside resolved solid mesh'):stressDisplay==='utilisation'?((displayedStress(pole,stationAt(result,height),x,y,height,'utilisation',solid)??0)*100).toFixed(1)+'% timber utilisation':displayStress(Math.abs(stress/1e6),units).toFixed(2)+' '+unitLabels[units].stress+' '+(stressDisplay==='shear'?'fibre shear':stress<0?'compression':'tension'));}else setProbe(c.drilled?'Drill bore · material removed':c.voided?'Cavity · material removed':c.knot?'Knot · prescribed grain deviation':c.severity>0?'Decay · '+Math.round(c.severity*100)+'% local severity':'Sound wood');
 }
 return <>{view==='Innerview'&&<SketchToolbar drawing={drawing} setDrawing={setDrawing} kind={sketchKind} setKind={setSketchKind}/>} {drawing&&<p className="sketch-hint">Draw and release, or click corners and double-click to finish. Escape cancels.</p>}<div className={'section-visual '+(view==='Stresses'?'stress-section':'')}><span className="north-label">N</span><div className="section-crosshair x"/><div className="section-crosshair y"/><div className="section-canvas-wrap" ref={wrap}><canvas width={512} height={512} ref={canvas} title="Scroll up or down the pole" tabIndex={0} onDoubleClick={()=>{if(testBearing===undefined)zoom.current=1;schedule();}} onKeyDown={e=>{if(e.key==='Escape'&&testDrag.current!==null){testDrag.current=null;onTestBearing?.(testStart.current);}if(e.key==='ArrowUp'||e.key==='ArrowDown'){e.preventDefault();onHeight(clamp(z+(e.key==='ArrowUp'?.05:-.05),-pole.embedment,pole.length-pole.embedment));}}} onPointerDown={e=>{if(testBearing===undefined||e.button!==0)return;const box=e.currentTarget.getBoundingClientRect(),x=e.clientX-box.left-box.width/2,y=box.height/2-(e.clientY-box.top),r=diameterAt(pole,z)/2/(diameterAt(pole,z)/2+PROBE_OUTER_REACH+.02)*box.width*.46;if(Math.hypot(x,y)<r)return;const a=(Math.atan2(x,y)*180/Math.PI+360)%360;testDrag.current=a-testBearing;testStart.current=testBearing;e.currentTarget.setPointerCapture(e.pointerId);e.preventDefault();}} onPointerUp={e=>{testDrag.current=null;if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);}} onLostPointerCapture={()=>{if(testDrag.current!==null){testDrag.current=null;onTestBearing?.(testStart.current);}}} onPointerCancel={()=>{testDrag.current=null;onTestBearing?.(testStart.current);}} onPointerMove={inspect} onPointerLeave={()=>setProbe('Move over the section to inspect')}/>{testBearing===undefined&&<SectionSketch pole={pole} z={z} selected={selected} zoom={()=>zoom.current} onAdd={onAdd} onEdit={onEdit} onSelect={onSelect} onMessage={onMessage} drawing={drawing} kind={sketchKind} onFinish={()=>setDrawing(false)}/>}</div>{scan&&<div className="acoustic-path"><span/><i/></div>}<span ref={diameter} className="section-diameter"/><span className="section-live-status" ref={status}/><div className="section-probe">{probe}{view==='Stresses'&&solid&&inLocalZone(pole,solid,z)&&<small>Local 3D preview</small>}</div></div></>;
});
