import {defectSectionLoops,moveDefectSection} from '../domain/defectEditing.ts';
import {useEffect,useRef,useState} from 'react';
import {clamp,defectDistance,diameterAt,regionScale,type PoleCase,type Region} from '../domain/model.ts';
import {normaliseSketch,type Point2} from '../domain/sketch.ts';
import {sectionReferenceRadius} from '../scene/sectionGeometry.ts';
export interface SketchProps {pole:PoleCase;z:number;selected?:string|null;zoom:()=>number;onAdd?:(r:Region)=>void;onEdit?:(id:string,update:Partial<Region>)=>void;onSelect?:(id:string)=>void;onMessage?:(text:string)=>void}
export function SketchToolbar({drawing,setDrawing,kind,setKind}:{drawing:boolean;setDrawing:(v:boolean)=>void;kind:'void'|'decay';setKind:(v:'void'|'decay')=>void}){return <div className="sketch-toolbar"><button className={drawing?'selected':''} onClick={()=>setDrawing(!drawing)}>{drawing?'Cancel sketch':'Sketch a defect'}</button><select aria-label="Sketch defect type" value={kind} onChange={e=>setKind(e.target.value as 'void'|'decay')}><option value="void">Cavity</option><option value="decay">Decay</option></select></div>;}
export default function SectionSketch(props:SketchProps&{drawing:boolean;kind:'void'|'decay';onFinish:()=>void}){
 const {pole,z,drawing}=props,[preview,setPreview]=useState<Point2[]>([]),clickPoints=useRef<Point2[]>([]),gesture=useRef<{points:Point2[];start:Point2;region?:Region;dx:number;dy:number}|null>(null);
 useEffect(()=>{if(!drawing){gesture.current=null;clickPoints.current=[];setPreview([]);}},[drawing]);
 const reference=()=>sectionReferenceRadius(pole)/props.zoom(),map=(q:Point2):Point2=>[50+q[0]/reference()*46,50-q[1]/reference()*46];
 const point=(e:React.PointerEvent<SVGSVGElement>):Point2=>{const b=e.currentTarget.getBoundingClientRect(),r=reference();return [((e.clientX-b.left)/b.width-.5)*r/.46,(.5-(e.clientY-b.top)/b.height)*r/.46];};
 function outline(r:Region,dx=0,dy=0):Point2[]{return defectSectionLoops(pole,{...r,...moveDefectSection(pole,r,dx,dy)},z)[r.decay?.pattern==='shell'?1:0]??[];}
 const visible=pole.regions.filter(r=>r.shape.type!=='section-contours'&&z>=r.zMin&&z<=r.zMax);
 const path=(r:Region)=>defectSectionLoops(pole,r,z).map(loop=>'M'+loop.map(q=>map(q).join(',')).join('L')+'Z').join('');
 function down(e:React.PointerEvent<SVGSVGElement>){if(e.button!==0)return;const q=point(e),r=visible.filter(r=>defectDistance(pole,r,...q,z)<=1).sort((a,b)=>a.id===props.selected?-1:b.id===props.selected?1:visible.indexOf(b)-visible.indexOf(a))[0];if(!drawing&&!r)return;if(drawing&&Math.hypot(...q)>diameterAt(pole,z)/2){props.onMessage?.('Start the outline inside the pole.');return;}e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);gesture.current={points:[q],start:q,region:drawing?undefined:r,dx:0,dy:0};if(r&&!drawing)props.onSelect?.(r.id);setPreview(r&&!drawing?outline(r):[q]);}
 function move(e:React.PointerEvent<SVGSVGElement>){const g=gesture.current;if(!g)return;const q=point(e);if(g.region){g.dx=q[0]-g.start[0];g.dy=q[1]-g.start[1];setPreview(outline(g.region,g.dx,g.dy));}else{const last=g.points.at(-1)!;if(Math.hypot(q[0]-last[0],q[1]-last[1])>reference()*.012){g.points.push(q);setPreview([...g.points]);}}}
 function finish(e:React.PointerEvent<SVGSVGElement>,cancel=false){const g=gesture.current;gesture.current=null;setPreview([]);if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);if(!g||cancel)return;
  if(g.region){if(Math.hypot(g.dx,g.dy)>1e-6)props.onEdit?.(g.region.id,moveDefectSection(pole,g.region,g.dx,g.dy));return;}
  if(g.points.length===1){const q=g.points[0],last=clickPoints.current.at(-1);if(!last||Math.hypot(q[0]-last[0],q[1]-last[1])>reference()*.012)clickPoints.current.push(q);setPreview([...clickPoints.current]);return;}commit(g.points);
 }
 function commit(input:Point2[]){try {let points=input;if(points.length>128)points=Array.from({length:128},(_,i)=>points[Math.floor(i*points.length/128)]);if(points.length>3&&Math.hypot(points[0][0]-points.at(-1)![0],points[0][1]-points.at(-1)![1])<reference()*.025)points=points.slice(0,-1);const shape=normaliseSketch(points),centre=clamp(z,-pole.embedment+.01,pole.length-pole.embedment-.01),half=Math.min(.3,centre+pole.embedment,pole.length-pole.embedment-centre);props.onAdd?.({id:crypto.randomUUID(),name:props.kind==='void'?'Sketched cavity':'Sketched decay',kind:props.kind,zMin:centre-half,zMax:centre+half,severity:.7,shape,provenance:'synthetic'});clickPoints.current=[];setPreview([]);props.onFinish();}catch(error){props.onMessage?.(error instanceof Error?error.message:'Draw a simple closed shape.');}}
 return <svg className={'section-sketch '+(drawing?'drawing':'')} viewBox="0 0 100 100" aria-label="Sketch and move defects in the section" tabIndex={drawing?0:-1} onKeyDown={e=>{if(e.key==='Enter'&&drawing)commit(clickPoints.current);}} onDoubleClick={()=>{if(drawing)commit(clickPoints.current);}} onPointerDown={down} onPointerMove={move} onPointerUp={e=>finish(e)} onPointerCancel={e=>finish(e,true)}>{visible.map(r=><path key={r.id} data-defect-id={r.id} className={props.selected===r.id?'selected':''} d={path(r)} fillRule="evenodd"><title>{r.name} · drag to move</title></path>)}{preview.length>0&&<polyline className="sketch-preview" points={preview.map(q=>map(q).join(',')).join(' ')}/>}</svg>;
}
