import {useMemo,type RefObject} from 'react';
import type {WaveSequence} from '../inspection/waveSimulation.ts';
import {signalEnvelope} from '../inspection/signalEnvelope.ts';
import './signalEnvelope.css';
export default function SignalEnvelope({sequence,showReference,stale,playhead}:{sequence:WaveSequence|null;showReference:boolean;stale:boolean;playhead:RefObject<SVGLineElement|null>}){
 const data=useMemo(()=>sequence?signalEnvelope(sequence.trace,sequence.reference,sequence.duration,sequence.frequency):null,[sequence]);
 if(!sequence||!data)return <p className="field-note">Filtered signal will appear when the wave calculation is ready.</p>;
 if(!data.hasReference)return <p className="field-note">Filtered signal percentages unavailable: the sound reference has no amplitude.</p>;
 const w=512,h=286,left=60,right=16,top=20,bottom=48,pw=w-left-right,ph=h-top-bottom,n=data.actual.length,max=Math.max(1,...data.actual,...(showReference?data.reference:[])),ceiling=Math.ceil(max*4)/4;
 const x=(i:number)=>left+i/(n-1)*pw,y=(v:number)=>top+ph-v/ceiling*ph,path=(values:Float64Array)=>Array.from(values,(v,i)=>`${i?'L':'M'}${x(i).toFixed(2)},${y(v).toFixed(2)}`).join(' '),pct=(v:number|null)=>v===null?'—':`${(v*100).toFixed(1)}%`;
 return <section className="signal-envelope" aria-label="Simulated filtered amplitude"><div className="envelope-heading"><strong>Filtered amplitude</strong><span>Simulated receiver envelope</span></div><svg viewBox={`0 0 ${w} ${h}`} role="img" aria-label={`Filtered amplitude against time samples. Peak ${pct(data.peakRatio)} of the sound reference.`}>
 <rect width={w} height={h} rx="8" fill="#10191f"/>{[0,.25,.5,.75,1].map(f=><g key={f}><line x1={left} x2={w-right} y1={y(f*ceiling)} y2={y(f*ceiling)} stroke="#455159" strokeWidth=".7"/><text x={left-9} y={y(f*ceiling)+4} textAnchor="end">{Math.round(f*ceiling*100)}</text></g>)}{[0,.25,.5,.75,1].map(f=><g key={f}><line x1={left+pw*f} x2={left+pw*f} y1={top} y2={h-bottom} stroke="#455159" strokeWidth=".7"/><text x={left+pw*f} y={h-bottom+20} textAnchor="middle">{Math.round((n-1)*f)}</text></g>)}
 {showReference&&<path d={path(data.reference)} fill="none" stroke="#a6b4bd" strokeWidth="1.5" strokeDasharray="5 4"/>}<path d={path(data.actual)} fill="none" stroke="#9dcea2" strokeWidth="3.5" strokeLinejoin="round" strokeLinecap="round"/>{data.peaks.map(i=><circle key={i} cx={x(i)} cy={y(data.actual[i])} r="4.5" fill="#9dcea2" stroke="#fff" strokeWidth="2"/>)}<line ref={playhead} x1={left} x2={left} y1={top} y2={h-bottom} stroke="#ecaa57" strokeWidth="1.4" opacity=".8"/><text x={left+pw/2} y={h-10} textAnchor="middle">Time samples</text><text transform={`translate(16 ${top+ph/2}) rotate(-90)`} textAnchor="middle">Amplitude (% sound peak)</text></svg>
 <div className="envelope-key"><span><i/>Section</span>{showReference&&<span><i className="reference"/>Sound reference</span>}<span>{Math.round(sequence.duration*1e6)} µs across {n} samples</span></div>
 {stale&&<p className="envelope-stale">Previous calculation · {sequence.height.toFixed(2)} m / {sequence.bearing}°</p>}
 <dl className="envelope-metrics"><div><dt>Height AGL</dt><dd>{Math.round(sequence.height*1000)} <small>mm</small></dd></div><div><dt>Arrival indicator</dt><dd>{data.arrivalSeconds===null?'—':Math.round(data.arrivalSeconds*1e6)} <small>µs</small></dd></div><div><dt>Peak amplitude</dt><dd>{pct(data.peakRatio)}</dd></div><div><dt>Signal energy proxy</dt><dd>{pct(data.energyRatio)}</dd></div></dl>
 <details className="envelope-method"><summary>How this graph is calculated</summary><p>One-period moving RMS of the simulated receiver displacement ({Math.round(data.windowSeconds*1e6)} µs window). The section and sound reference share the sound-envelope peak scale; values can exceed 100%. White markers identify up to two separated envelope peaks, not heart or shell pathways.</p><p>Arrival indicator: first raw sample reaching 5% of the sound signal’s peak, measured from the simulation clock. This includes source pulse timing; it is not calibrated UB1000 time of flight. Energy proxy: integrated squared displacement relative to sound timber, not measured acoustic energy or strength.</p><p>The screenshot’s Heart Energy and Shell Energy definitions, filter and sampling calibration have not been supplied. This graph does not assign those names or imitate its numerical readings.</p></details></section>;
}
