import assert from 'node:assert/strict';
import fs from 'node:fs';
import {defaultCase} from '../../src/domain/model.ts';
import {poleMesh,endLoads,eligibleRegion} from '../../src/analysis/solid/mesh.ts';
import {geometry,elementK,stress,orthotropicD,solveSolid} from '../../src/analysis/solid/kernel.ts';
const records=[];function check(name,value,limit){records.push({name,value,limit,pass:value<=limit});assert.ok(value<=limit,`${name}: ${value} > ${limit}`);}
const p=defaultCase();p.soil='Fixed';p.diameters={butt:.3,ground:.3,tip:.3};p.regions=[{id:'cavity',name:'Enclosed hollow',kind:'void',zMin:1.6,zMax:2.2,severity:1,shape:{type:'ellipse',centreX:.02,centreY:0,radiusX:.06,radiusY:.07,angle:0,profile:'rounded'},provenance:'synthetic'}];
const resolution={angular:8,axial:4,radial:1,marginDiameters:2},D=orthotropicD(p.material.E),m=poleMesh(p,resolution),g=geometry(m.points,m.tets[0]),K=elementK(g.inv,g.volume,D),scale=Math.max(...K.map(Math.abs)),ps=m.tets[0].map(n=>m.points[n]);
check('Element symmetry',Math.max(...K.map((v,i)=>Math.abs(v-K[(i%30)*30+Math.floor(i/30)])))/scale,1e-13);
for(let mode=0;mode<6;mode++){const u=ps.flatMap(([x,y,z])=>mode<3?[+(mode===0),+(mode===1),+(mode===2)]:mode===3?[0,-z,y]:mode===4?[z,0,-x]:[-y,x,0]),f=Array.from({length:30},(_,i)=>u.reduce((s,v,j)=>s+K[i*30+j]*v,0));check(`Rigid mode ${mode+1}`,Math.max(...f.map(Math.abs))/scale,1e-12);}
const A=[[.002,.003,-.001],[.001,-.002,.001],[.003,-.001,.004]],u=ps.flatMap(v=>A.map(row=>row.reduce((s,a,i)=>s+a*v[i],0))),eps=[.002,-.002,.004,.004,0,.002],exact=D.map(row=>row.reduce((s,d,i)=>s+d*eps[i],0));
for(const q of [[.25,.25,.25,.25],[.1,.2,.3,.4]])check('Affine strain and signed stress',Math.max(...stress(g.inv,q,D,u).map((s,i)=>Math.abs(s-exact[i])))/Math.max(...exact.map(Math.abs)),1e-11);
const allFaces=new Map();for(const ns of m.tets)for(const f of [[0,1,2],[0,1,3],[0,2,3],[1,2,3]]){const k=f.map(i=>ns[i]).sort((a,b)=>a-b).join(',');allFaces.set(k,(allFaces.get(k)??0)+1);}check('Mesh face ownership',Math.max(...allFaces.values())-2,0);check('Physical boundary faces',Math.abs([...allFaces.values()].filter(v=>v===1).length-m.surface.length),0);
const force=[1000,0,0],bending=[1000*(p.length-p.embedment-m.zMax),0],loads=endLoads(m,force,bending),fixed=new Map(m.bottom.flatMap(n=>[0,1,2].map(k=>[3*n+k,0])));
function resultant(values,nodes=m.points.map((_,i)=>i)){const F=[0,0,0],M=[0,0,0];nodes.forEach(n=>{const [x,y,z]=m.points[n],[fx,fy,fz]=values.slice(3*n,3*n+3);F[0]+=fx;F[1]+=fy;F[2]+=fz;M[0]+=y*fz-z*fy;M[1]+=z*fx-x*fz;M[2]+=x*fy-y*fx;});return {F,M};}
const applied=resultant(loads);check('Transferred force',Math.hypot(...applied.F.map((v,i)=>v-force[i]))/1000,1e-12);check('Transferred moment',Math.hypot(applied.M[0],applied.M[1]-1000*(p.length-p.embedment),applied.M[2])/10000,1e-12);
const s=solveSolid(m,D,loads,fixed),reaction=resultant(s.internal,m.bottom);check('External force balance',Math.hypot(...reaction.F.map((v,i)=>v+applied.F[i]))/1000,1e-6);check('External moment balance',Math.hypot(...reaction.M.map((v,i)=>v+applied.M[i]))/10000,1e-6);check('Energy / work',Math.abs(2*s.energy-loads.reduce((v,f,i)=>v+f*s.displacements[i],0))/(2*s.energy),1e-7);
const reversed=solveSolid(m,D,Float64Array.from(loads,v=>-v),fixed);check('Load reversal',Math.max(...s.displacements.map((v,i)=>Math.abs(v+reversed.displacements[i]))),1e-12);const zero=solveSolid(m,D,new Float64Array(loads.length),fixed);check('Zero load',Math.max(...zero.displacements.map(Math.abs)),0);
const solid=structuredClone(p);solid.regions[0].kind='decay';solid.regions[0].severity=0;const sm=poleMesh(solid,resolution),kappa=.01,eu=sm.points.flatMap(([x,y,z])=>[kappa*(z-sm.zMin)**2/2,0,-kappa*x*(z-sm.zMin)]),bc=new Map();sm.points.forEach((q,n)=>{if(Math.abs(q[2]-sm.zMin)<1e-9||Math.abs(q[2]-sm.zMax)<1e-9)for(let k=0;k<3;k++)bc.set(3*n+k,eu[3*n+k]);});const b=solveSolid(sm,orthotropicD(p.material.E,.1,.065,0,0),new Float64Array(eu.length),bc);check('Exact quadratic bending displacement',Math.max(...b.displacements.map((v,i)=>Math.abs(v-eu[i])))/Math.max(...eu.map(Math.abs)),2e-6);check('Exact longitudinal bending stress',Math.max(...sm.tets.map((ns,i)=>Math.abs(b.centroidStress[i][2]+p.material.E*kappa*ns.slice(0,4).reduce((a,n)=>a+sm.points[n][0]/4,0))))/(p.material.E*kappa*.15),2e-6);
for(const kind of ['knot','multiple','surface','ground']){const bad=structuredClone(p);if(kind==='knot')bad.regions[0].kind='knot';if(kind==='multiple')bad.regions.push({...bad.regions[0],id:'second'});if(kind==='surface')bad.regions[0].shape.radiusX=.15;if(kind==='ground')bad.regions[0].zMin=-.2;let rejected=false;try{eligibleRegion(bad);}catch{rejected=true;}check(`Reject ${kind}`,rejected?0:1,0);}
let rejected=false;try{solveSolid(m,D,loads,fixed,{maxIterations:1});}catch{rejected=true;}check('Reject nonconvergence',rejected?0:1,0);
fs.writeFileSync('verification/p05/reference-input.json',JSON.stringify({mesh:m,E:p.material.E,force,bending,loads:[...loads],displacements:[...s.displacements],energy:s.energy,stress:s.centroidStress}));fs.writeFileSync('verification/results/p05-kernel.json',JSON.stringify({records,elapsedMs:s.elapsedMs,iterations:s.iterations,scope:'Kernel verification, not peak convergence or physical validation.'},null,2));console.log(`${records.length} P05 kernel checks passed.`);
